### ISSUE TITLE
Fix tagset of language specific FEs

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-tc#123]
Originally reported on Google Code with ID 123

```
We have several FEs that are POS tag set or language specific without declaring so.
They should either fail or at least warn if used incorrectly.
```

Reported by `torsten.zesch` on 2014-05-08 17:37:26

**Comment by Horsmann** [comment]
A list of the affected FEs would be helpful. I found in the `getDocumentPhoneticNgrams()` in `tc-features-ngram/NgramUtil.java` a explicit check for 2 supported languages and an exception if neither language is found. Do you remember which other FEs have hardcoded language checks?

**Comment by zesch** [comment]
No. I think the nature of this bug is that we don't really know which FEs are effected which might lead to unexpected behavior.
