### ISSUE TITLE
Add test cases for FeatureExtractors

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-tc#169]
Originally reported on Google Code with ID 169

```
We currently only have test cases for DocumentFeatureExtractors. We should add test
cases for ClassificationUnitFeatureExtractors as well

```

Reported by `daxenberger.j` on 2014-07-25 07:22:51

**Comment by Horsmann** [comment]
@daxenberger What exactly is the difference to https://github.com/dkpro/dkpro-tc/issues/9 ? Looks like a duplicate?

**Comment by daxenberger** [comment]
more specific than #9. I'd suggest to close #9 and leave this one open.

**Comment by Horsmann** [comment]
I move this one to 0.9.0, too. I assume we find no one willing to implement all those needed tests in the very near future (i.e. by end of the next week).
