### ISSUE TITLE
Users should only be required to set the report type (for standard reports) - ML adapter should then provide the right instances

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-tc#180]
Originally reported on Google Code with ID 180

```
Currently, when e.g. switching from Weka to another ML framework, the user also has
to replace all reports, as they are called WekaClassificationReport etc.
It would be better if the user only had to select a certain type of report and the
ML framework would figure out which instance to apply.

```

Reported by `torsten.zesch` on 2014-09-09 11:52:32

**Comment by Horsmann** [comment]
Are there any reports left that have to be explicitly specified by the user? It is still necessary to add the `TrainTestReport` or `CrossvalidationReport`but neither is MLA dependent (anymore)?

**Comment by Horsmann** [comment]
@daxenberger ?

**Comment by Horsmann** [comment]
@daxenberger @zesch

**Comment by zesch** [comment]
If you think that no ML-specfic reports are remaining, please close the issue.
It can be re-opened later otherwise.
