### ISSUE TITLE
Broken tests in dkpro-tc-features-readability

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-tc#218]
Originally reported on Google Code with ID 218

```
Most of the tests in dkpro-tc-features-readability are failing (currently ignored).
@Lisa: could you please have a look at what might be going wrong here?

```

Reported by `daxenberger.j` on 2014-12-04 14:13:19

**Comment by Horsmann** [comment]
@how-ever-fixes-this Once the test-cases are working please remove the property from the `pom.xml` that excludes this project from being released

**Comment by Horsmann** [comment]
@zesch @daxenberger Are there any real plans to fix this issue or can we dump the `dead code project`?

**Comment by zesch** [comment]
Most of these features are now used in other projects e.g. the cTest generation.
They have been refactored there, so I guess we should remove them.

**Comment by daxenberger** [comment]
I guess this module will not be further developed. Has been excluded from previous releases and should be excluded from the next one. 
From my side, it can also be deleted in the snapshot.

**Comment by Horsmann** [comment]
ok. I delete the project then.
