### ISSUE TITLE
Verify that experiment name does not include special characters

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-tc#221]
Originally reported on Google Code with ID 221

```
Special characters in experiment names (e.g. "/") cause DKPro Lab to throw unexpected
exceptions. We should check that beforehand to avoid confusion. As dev mailing list
discussion for details.
```

Reported by `daxenberger.j` on 2014-12-09 08:44:19

**Comment by Horsmann** [comment]
This bug is best handled in the Experiment_ImplBase

I think it is easier to define what is allowed than what is not. 
How about
a-z, A-Z, 0-9, hyphen, underscore

I would then auto-replace each illegal character with a hyphen or do you see any problems  with that?

**Comment by zesch** [comment]
This might not work, e.g. if the illegal character is the first in the string this could lead to serious problems downstream.

Maybe just throw a meaningful exception and let the user select a better name? :)

**Comment by Horsmann** [comment]
An exception is throw if anything other than [a-zA-Z0-9-_] is found in the name
