### ISSUE TITLE
Possible duplicate FE TypeTokenRatio

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-tc#226]
Originally reported on Google Code with ID 226

```
We now have TypeTokenRatio FE in style and readability.

Do they have the same functionality? 
Then maybe we should remove one.

```

Reported by `torsten.zesch` on 2014-12-12 21:10:56

**Comment by zesch** [comment]
The one in readability is more comprehensive than the one in style, but people might not be looking in readability for TTR features.
I am unsure how to resolve this.

**Comment by reckart** [comment]
Create an overview over all FEs in Asciidoc ;)

**Comment by Horsmann** [comment]
@zesch @daxenberger Delete the FE in `features` and move the one from `readability` into the more general package?

**Comment by daxenberger** [comment]
ok.
Richard's suggestions is also nice. We should have auto-generated Asciidoc for a list of all features.

**Comment by Horsmann** [comment]
how do I ascii auto-generate only over FEs?

**Comment by reckart** [comment]
E.g. by writing a groovy script that parses the Java files and extracts names, descriptions, and parameters from the FE source code and renders that into a nice table. 

I have done similar things to auto-generate the DKPro Core reference documentation. But for DKPro Core, I didn't have to parse Java directly - I could use XML descriptors generated by uimaFIT. But we don't have a XML fragment generator for external resources, so it would be necessary to go directly into the code. Well, parsing the class files would in principle also work.

Anyway, it would be something for the next release, not the present one.

**Comment by Horsmann** [comment]
Dead issue as it seems after removing the readability project.
