### ISSUE TITLE
Make use of ngramFreqThreshold or remove it

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-tc#244]
The ngramFreqThreshold parameter in the NGram module is not used by any (child) feature extractor. That is misleading. Furthermore, its functionality (min. frequency-based ngram selection rather than absolute number) would be helpful.

**Comment by daxenberger** [comment]
This has been fixed for frequency-based FEs (cf. #246). TODO: fix for Lucene-based ones.

**Comment by mwunderlich** [comment]
I have just sent another pull request with the changes for Lucence-based FEs.

**Comment by daxenberger** [comment]
Thanks!! To summarize: we now have the ngramFreqThreshold parameter for Frequency Distribution and Lucene based ngram FEs. By default, ngramFreqThreshold will not be applied (unless set by the user, in which case it will definitely by applied). topK parameter remains as is, default value is applied unless otherwise specified.

I guess this can be closed.
