### ISSUE TITLE
Add .gitignore in TC root folder

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#245]
There is no central .gitignore file yet

**Comment by Horsmann** [comment]
The last commit excluded 
.settings
.classpath
.project

which is the same as for dkpro-core.
Anything on top of this that one should exclude?

**Comment by reckart** [comment]
"target" is a typical exclusion - I wonder if that is not also in the dkpro-core .gitignore.

**Comment by logological** [comment]
There's [a list of recommended .gitignore entries per language and environment](https://github.com/github/gitignore).  Of interest are the ones for Java and Maven, which contain some lines not already in DKPro TC and DKPro Core's. Some of the lines are pretty obscure (but probably harmless to include anyway) but others could be useful.  `**/target/` is probably good for multi-module Maven projects, and `hs_err_pid*` could be useful if you invoke Java from the command line.
