### ISSUE TITLE
BatchCrossValidationReport throws ArrayIndexOutOfBoundsException when external resources are used

### ISSUE THREAD

**Issue by logological** [dkpro/dkpro-tc#253]
When I define an external resource and pass it to a feature extractor using Groovy, my cross-validation experiments fail with an ArrayIndexOutOfBoundsException in BatchCrossValidationReport:

```
Exception in thread "main" de.tudarmstadt.ukp.dkpro.lab.engine.LifeCycleException: java.lang.ArrayIndexOutOfBoundsException: 0
    at de.tudarmstadt.ukp.dkpro.lab.engine.impl.DefaultLifeCycleManager.complete(DefaultLifeCycleManager.java:98)
    at de.tudarmstadt.ukp.dkpro.lab.engine.impl.ExecutableTaskEngine.run(ExecutableTaskEngine.java:72)
    at de.tudarmstadt.ukp.dkpro.lab.engine.impl.DefaultTaskExecutionService.run(DefaultTaskExecutionService.java:48)
    at de.tudarmstadt.ukp.dkpro.lab.Lab.run(Lab.java:97)
    at de.tudarmstadt.ukp.dkpro.lab.Lab$run$0.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at de.tudarmstadt.ukp.dkpro.tc.groovyexamples.single.unit.BrownUnitPosExternalResourceDemo.runCrossValidation(BrownUnitPosExternalResourceDemo.groovy:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at de.tudarmstadt.ukp.dkpro.tc.groovyexamples.single.unit.BrownUnitPosExternalResourceDemo.main(BrownUnitPosExternalResourceDemo.groovy:123)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
    at de.tudarmstadt.ukp.dkpro.tc.ml.report.BatchCrossValidationReport.execute(BatchCrossValidationReport.java:106)
    at de.tudarmstadt.ukp.dkpro.lab.engine.impl.DefaultLifeCycleManager.complete(DefaultLifeCycleManager.java:91)
    ... 18 more
```

We do not currently have any Groovy examples demonstrating how to use external resources, so I will commit one.

**Comment by logological** [comment]
In Commit 38585fc053da1db38637a71546a93907b0e640f6 I added de.tudarmstadt.ukp.dkpro.tc.groovyexamples.singleunit.BrownUnitPosExternalResourceDemo to the dkpro-tc-examples-groovy module.  This is an example of how to pass an external resource to a feature extractor in Groovy.  it triggers the above-noted crash.

**Comment by logological** [comment]
On further testing, I think the proximate cause is that the `evaluation_results.csv` file which `de.tudarmstadt.ukp.dkpro.tc.ml.report.BatchCrossValidationReport.execute()` tries to read is not in the expected format.  In experiments which do not pass external resources to the feature extractors, the CSV files are relatively "normal" in that every logical line in the file corresponds to a single physical line.  However, in an experiment with external resources, the CSV file contains fields with embedded newlines such as the following:

```
"WekaTestTask-BrownPosExternalResourceDemo-CV-Groovy-636bb90c-2afb-11e5-ac75-3d8db05bb8c9","/home/miller/opt/dkpro/de.tudarmstadt.ukp.dkpro.lab/repository/PreprocessTask-BrownPosExternalResourceDemo-CV-Groovy-5b17ead7-2afb-11e5-ac75-3d8db05bb8c9/preprocessorOutputTrain","0.0","0.0","0.0","unit","0.0","0.0","0.0","false","0.0","0.0","0.0","0.0","0.0","0.0","0.0","0","0.0","0.0","0.0","singleLabel","0.36538461538461536","0.0","0.0","57.0","0.0","0.0","0.0","0.0","[de.tudarmstadt.ukp.dkpro.tc.features.length.NrOfTokensUFE]","0.0","0.0","0.2235294117647059","0.0","0.0","null","0.0","0.0","0.0","0.0","1.0","0.0","0.0","0.0","0.0","null","0.0","[]","0.0","0.0","0.2235294117647059","0.0","0.0","0.0","0.0","null","0.0","0.0","0.0","false","false","0.0","0.0","0.0","[weka.classifiers.functions.SMO]","null","0.08167420814479638","198.0","0.0","0.0","22.352941176470587","0.0","0.0","0.0","0.0","0.0","0.0","0.0","0.049965397923875436","0.0","0.0","0.0","0.0","0.0","0.0","0.0","0.0","singleLabel","unit","0.0","0.0","0.0","0.0","0.0","null","[DummyResource, org.apache.uima.fit.internal.ExtendedExternalResourceDescription_impl: 
description = NULL
implementationName = NULL
name = de.tudarmstadt.ukp.dkpro.tc.groovyexamples.single.unit.DummyResource-0
resourceSpecifier = org.apache.uima.resource.impl.CustomResourceSpecifier_impl: 
parameters = Array{0: org.apache.uima.resource.impl.Parameter_impl: 
name = __UIMAFIT_RESOURCE_NAME__
value = de.tudarmstadt.ukp.dkpro.tc.groovyexamples.single.unit.DummyResource-0

}

resourceClassName = de.tudarmstadt.ukp.dkpro.tc.groovyexamples.single.unit.DummyResource

]","0.0","/home/miller/opt/dkpro/de.tudarmstadt.ukp.dkpro.lab/repository/PreprocessTask-BrownPosExternalResourceDemo-CV-Groovy-5b17ead7-2afb-11e5-ac75-3d8db05bb8c9/preprocessorOutputTrain","0.0","0.0","null","0.0","[de.tudarmstadt.ukp.dkpro.tc.features.length.NrOfTokensUFE]","0.0","0.0","[de.tudarmstadt.ukp.dkpro.tc.features.length.NrOfTokensUFE]","0.0","0.0","0.0","0.0","0.0","0.0","false","[DummyResource, org.apache.uima.fit.internal.ExtendedExternalResourceDescription_impl: 
description = NULL
implementationName = NULL
name = de.tudarmstadt.ukp.dkpro.tc.groovyexamples.single.unit.DummyResource-0
resourceSpecifier = org.apache.uima.resource.impl.CustomResourceSpecifier_impl: 
parameters = Array{0: org.apache.uima.resource.impl.Parameter_impl: 
name = __UIMAFIT_RESOURCE_NAME__
value = de.tudarmstadt.ukp.dkpro.tc.groovyexamples.single.unit.DummyResource-0

}

resourceClassName = de.tudarmstadt.ukp.dkpro.tc.groovyexamples.single.unit.DummyResource

]","0.0","0.0","0.0","0.0","0.0","0.0","0.0","0.0","0.0","0.0","0.0","0.0","0.0","unit","0.0","0.0","0.0","77.6470588235294","0.0","0.0","null","0.0","[DummyResource, org.apache.uima.fit.internal.ExtendedExternalResourceDescription_impl: 
description = NULL
implementationName = NULL
name = de.tudarmstadt.ukp.dkpro.tc.groovyexamples.single.unit.DummyResource-0
resourceSpecifier = org.apache.uima.resource.impl.CustomResourceSpecifier_impl: 
parameters = Array{0: org.apache.uima.resource.impl.Parameter_impl: 
name = __UIMAFIT_RESOURCE_NAME__
value = de.tudarmstadt.ukp.dkpro.tc.groovyexamples.single.unit.DummyResource-0

}

resourceClassName = de.tudarmstadt.ukp.dkpro.tc.groovyexamples.single.unit.DummyResource

]","0.0","0.0","0.0","0.0","0.0","0.0","0.0","0.0","0.0","null","null","null","null","null","null","null","null","null","null","null","null","null","null","null","null","null","null","null","null","null","null","null","null","null"
```

I think the code we are using to parse the CSV files currently cannot handle fields with embedded newlines.

I'm not familiar with the Apache library this method uses to read the CSV files.  Possibly it is capable of handling fields with embedded newlines, but this functionality was not properly invoked by DKPro TC.  If it's not capable of handling fields with embedded newlines, then perhaps whatever class that produces the `evaluation_results.csv` file in the first place should replace them or strip them out before writing them.

(Note that the problem described in this report may not be specific to cross-validation experiments written in Groovy, but would also occur with ones written in pure Java.)

**Comment by logological** [comment]
Tracing further back, the `evaluation_results.csv` files are produced by `de.tudarmstadt.ukp.dkpro.tc.ml.report.BatchTrainTestReport.execute()`.  The newline-containing entries are read from `DISCRIMINATORS.txt` (where the newlines are escaped as `\n`) but when `de.tudarmstadt.ukp.dkpro.lab.reporting.FlexTable<V>` writes them to the CSV, it unescapes the newlines.

So there are a lot of different ways of fixing this behaviour:
1. Configure the Apache CSV reader to "correctly" interpret newlines within fields.  (IMHO newlines within fields are an abuse of the CSV format. Though I've often seen them in the wild, they make it very difficult to process the file with standard tools and approaches.)
2. Change the CSV output for `FlexTable` so that it replaces newlines within fields.
3. Change `de.tudarmstadt.ukp.dkpro.tc.ml.report.BatchTrainTestReport.execute()` so that it replaces newlines before adding them to the `FlexTable`.  For example, this could be effected by replacing line 112 with `cleanedDiscriminatorsMap.put(disc, discriminatorsMap.get(disc).replace('\n', ' '));`.
4. Change whatever code writes `DISCRIMINATORS.txt` to replace newlines before writing them.

I think Option 1 is a bad idea, but I'm not familiar enough with DKPro TC and DKPro Lab to know which of Options 2 to 4 (or even some other approach) is the best.  For example, maybe it's dangerous to replace the discriminator values because downstream code may be expecting them to exactly match how they were originally produced.

**Comment by reckart** [comment]
Newlines between quotes should have no special meaning in CSV files. Only newlines outside quotes are meaningful, no?

DISCRIMINATORS.txt is a properties file. Again, the Java Properties class should be smart enough to escape/unescape and kind of characters that have a special meaning in properties files. It should also handle UTF-8 (un)escaping.

I looks like the CSV reader from OpenCSV doesn't properly handle newlines between quotes. I didn't check the Apache Commons CSV code. IMHO it would be best to use a library which handles this properly - if one exists.

**Comment by reckart** [comment]
Looks like the CSV parser in Apache CSV is pretty competent and should be able to handle newlines between quotes nicely. 

http://grepcode.com/file/repo1.maven.org/maven2/org.apache.commons/commons-csv/1.1/org/apache/commons/csv/Lexer.java#Lexer

It would probably be good to replace OpenCSV with Apache Commons CSV in Lab just to be consistent:

**Comment by logological** [comment]
> Newlines between quotes should have no special meaning in CSV files. Only newlines outside quotes are meaningful, no?

That's correct, for certain fancy CSV formats. (There's no one standard CSV format.)

I looked again at `BatchCrossValidationReport`—it looks like it's not (fully) using a CSV reader at all.  Rather, it uses `org.apache.commons.io.FileUtils.readLines(File)` to read lines one at a time.  I think that method is file format–agnostic; it just treats the input as a text file.  The only CSV-specific processing `BatchCrossValidationReport` uses is when it passes the lines it reads to `org.apache.commons.lang.text.StrTokenizer.getCSVInstance(String)`.  But of course it's not passing complete lines in this case.

> It would probably be good to replace OpenCSV with Apache Commons CSV in Lab just to be consistent

The code we're discussing doesn't use OpenCSV; it uses Apache Commons IO and Apache Commons Lab.  But yes, the code should be using Apache Commons CSV instead.

**Comment by reckart** [comment]
That said, you'd probably not render external resource descriptions into a descriminator anyway. This sounds more like something I'd use a ClosureDimension for, specially in Groovy. The idea here is that you name your values, e.g.:

```
def dimTest = new ClosureDimension("test", [first: { "one" }, second: { "two" }])
```

What happens here is that we have a dimension with two values:
- first: { "one" }
- second: { "two" }

The values are actually named values. E.g. "first" it the name of the value that is stored in the DISCRIMINATORS.txt. During runtime, the actual values is obtained by evaluating the closure `{ "one" }`. This closure is an anonymous function that returns the string "one".

In your scenario, you'd replace "one" with a method call that creates the external resource description, e.g.

```
def dimLexicon = new ClosureDimension("lexicon", [first: { createWordnetResource() }, second: { createWiktionaryResource() }])
```

Now, what I don't know is whether you can use such a dimension with TC as is. 

In the last TC hackday, we continued working on allowing the additional of multiple instances of a FeatureExtractors with different configurations to a TC pipeline - this is technically related to the above, but not complete yet. Maybe you can try the ClosureDimension and report back.

See also: https://github.com/dkpro/dkpro-lab/blob/master/dkpro-lab-groovy/src/test/groovy/de/tudarmstadt/ukp/dkpro/lab/groovy/task/ClosureDimensionTest.groovy

**Comment by logological** [comment]
> That said, you'd probably not render external resource descriptions into a descriminator anyway.

I'm just following the example given in `de.tudarmstadt.ukp.dkpro.tc.examples.single.pair.ExternalResourceDemo` – I suspect that this is currently the only way of passing resources to feature extractors.  (I think it's problematic for some other reasons as well, for which I'll probably file a separate issue.)

**Comment by Horsmann** [comment]
I close this for now. No test case is available to verify if the error does still occur after countless changes to the backend.
