### ISSUE TITLE
TC model loading: .class files are not added to the classpath

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#255]
The current model loading still requires that the features are present in the classpath. TC itself does not really care about it anymore, but the underlying resource creation in UIMA complains if the resource (i.e. feature) that is used is not in the classpath. 

This worked in the past (for me) because I had the respective projects that defined those features in my dependency hierarchy without noticing it.

**Comment by Horsmann** [comment]
I added an inflection hack to add each of the .class files in the model folder to the classpath.
See TcAnnotatorUtil.java method addToClassPath();

Does anyone know an inflection-free way to add classes to the classpath?

**Comment by reckart** [comment]
Typically you would use a custom classloader. 

DKPro Core ResourceObjectProviderBase internally creates such a custom classloader in order to retrieve resources from auto-loaded JAR files.

There are some ways to configure UIMA to use a custom classloader for pipelines, but this is not accessible through uimaFIT - it would be necessary to use more basic UIMA API. E.g. UIMA uses this to support PEAR files which contain libraries inside.

However, this is all a bit fiddly.

As long as you add your model directly as a Maven dependency and do not rely on the auto-loading feature, it should work without custom classloaders. And when I say "it should work", I do not mean that it in the sense that "it should already work" but rather "if it doesn't work already, it should be made to work in that way".

**Comment by Horsmann** [comment]
Like I said, the loading of a model by TC does work. It is jsut at the point when UIMA creates the analysis engine when it is noticed that there are features which do no exist on the work space. Basically, adding the model does the trick for TC, but not for the UIMA part. UIMA is unaware that I have a folder in my model with class files I wish to be "noted as present and available". 

I wonder if the additional work load to sneak in a new class loader into UIMA is really worth the effort? Do you have some readings for what I would have to do?
The inflection solution are like 4 or 5 lines of code, where do you see problems if we would keep this?

**Comment by reckart** [comment]
Do you add the model as a Maven dependency?

Are the class files contained in a proper folder structure as mandated by the JAR specification, e.g. "org.lala.MyClass" should be in the JAR under "/org/lala/MyClass.class"?

The problem with the reflection-based approach (not inflection) is that it is not guaranteed to work on all Java platform implementations. You are not using a public API here.

**Comment by Horsmann** [comment]
Yes and no.

The attached screenshots shows the current structure. The ant-script installs the entire folder under the ...////flextag path being unaware of the features class files in this subfolder.

So, if I would get the package-as-maven-artifact thing working I could simply move the features out of there current subfolder? Just by adding the model-artifact one would get the respective features into the classpath?

![example](https://cloud.githubusercontent.com/assets/8234699/8874091/cb07b4ca-320d-11e5-815d-930d0efe9345.png)

**Comment by reckart** [comment]
If you moved the classes out of the `featureClassFolder` and into the JAR root, they would be on the classpath - actually they are already, but in a location where Java doesn't look for them. 

Of course, you'd risk that different models that use different versions of these feature extractors could clash with each other. That clash could only be avoided by using a custom classloader.

**Comment by Horsmann** [comment]
I think I prefer the custom classloader way. By placing the .class where java does not look for them it encapsulates the model better. I actually don't want that features defined in my models become _available_ to the project that uses the models. This is just an unexpected behavior. 

I looked into the `ResourceObjectProviderBase` that you mentioned. I am not sure which part of the code actually adds a class to the classpath? I found a call for `resolveLocation` which calls the class `ResourceUtils` that does something with a class loader, but I am not sure if that is what you meant?

**Comment by reckart** [comment]
That's what I meant. `ResourceObjectProviderBase` doesn't add anything to the root classloader (as your hack does), it uses its own custom classloader.

**Comment by Horsmann** [comment]
I am still unsure of how this works exactly. I have to trick UIMA not TC where and when would I have to place the custom class loader. The problem is that UIMA complains about a resource that is unknown. So how/where can I place an own loader that UIMA uses it?

**Comment by reckart** [comment]
In general, the UIMA ResourceManager has methods called setExtensionClassPath(...) that could be used. However, the resource manager is created before a pipeline is started, e.g. in `de.tudarmstadt.ukp.dkpro.lab.uima.engine.simple.SimpleExecutionEngine`.

**Comment by Horsmann** [comment]
That means I would need the awareness at program launch that I will use a TC trained model with user-defined features? This is supposed to be TC-local thing but it looks like it leaks down to the underlying UIMA framework. I wonder if such a solution is really preferable over reflection and keeping changes TC-local?

**Comment by reckart** [comment]
This is about FEs that are UIMA external resources, right?

**Comment by Horsmann** [comment]
Ehm, yes all FE inherit from `FeatureExtractorResource_ImplBase`

**Comment by reckart** [comment]
Hm, the problem happens inside FlexTag around this point here, I guess:

```
flexTagEngine = AnalysisEngineFactory.createEngine(TcAnnotatorSequence.class,
  TcAnnotatorSequence.PARAM_TC_MODEL_LOCATION, modelProvider.getResource(),
  TcAnnotatorSequence.PARAM_NAME_SEQUENCE_ANNOTATION, Sentence.class.getName(),
  TcAnnotatorSequence.PARAM_NAME_UNIT_ANNOTATION, Token.class.getName());
```

If yes, then it should be easy to solve I guess. `AnalysisEngineFactory.createEngine` internally creates a resource manager:

```
AnalysisEngineDescription aed = createEngineDescription(descriptorName, configurationData);
return UIMAFramework.produceAnalysisEngine(aed, ResourceManagerFactory.newResourceManager(), null);
```

If instead of calling `AnalysisEngineFactory.createEngine`, you would just do the above manually and while pass on your custom classloader to the `ResourceManager` created from `ResourceManagerFactory.newResourceManager()`, then UIMA should be able to find the FE classes.

**Comment by Horsmann** [comment]
This worked, thanks a lot :+1:
