### ISSUE TITLE
BrownCorpusReader duplicated in SVMhmm module

### ISSUE THREAD

**Issue by zesch** [dkpro/dkpro-tc#258]
Is there a deeper reason behind that (it is almost a verbatim copy of the version in examples).
The example also seems to work fine with the other version.
I think the one in the SVMhmm module could be deleted.

**Comment by daxenberger** [comment]
Maybe because ML modules should not have dependencies to the example modules (which are excluded from releases)?

**Comment by zesch** [comment]
That's what I thought in the first place, but the reader is only used by the SVMhmm example in the examples module and not in the ML module itself :)

**Comment by habernal** [comment]
Probably quick & dirty & bad refactoring from my side :) No deep reasons, feel free to delete it.
