### ISSUE TITLE
Shove documentation from wiki into asciidoc

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-tc#259]
Shove the information from the old Googlecode Wiki into asciidoc format.

**Comment by reckart** [comment]
Documentation auto-built by Jenkins:
- [User Guide](https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/DKPro%20TC%20Documentation%20%28GitHub%29/de.tudarmstadt.ukp.dkpro.tc$dkpro-tc-doc/doclinks/1/)
- [Developer Guide](https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/DKPro%20TC%20Documentation%20%28GitHub%29/de.tudarmstadt.ukp.dkpro.tc$dkpro-tc-doc/doclinks/2/)

**Comment by daxenberger** [comment]
Looks good. Thanks :)

**Comment by daxenberger** [comment]
Closing this. Documentation is moved.
