### ISSUE TITLE
id2outcome.java does not allow for spaces in labels

### ISSUE THREAD

**Issue by kulukimak** [dkpro/dkpro-tc#260]
_Releveant class:_

```
 dkpro-tc/dkpro-tc-evaluation/src/main/java/de/tudarmstadt/ukp/dkpro/tc/evaluation/Id2Outcome.java
```

_Relevant function:_

```
public static List<String> getLabels(String line) throws UnsupportedEncodingException
    {
        String[] numberedClasses = line.split(" ");
        List<String> labels = new ArrayList<String>();

        // filter #labels out and collect labels
        for (int i = 1; i < numberedClasses.length; i++) {
            // split one more time and take just the part with class name
            // e.g. 1=NPg, so take just right site
            String className = numberedClasses[i].split("=")[1];
            labels.add(URLDecoder.decode(className, "UTF-8"));
        }
        return labels;
    }
```

Since getLables() splits labels on spaces it does not allow for labels to contain spaces themselves:
_Relevant part:_

```
(String[] numberedClasses = line.split(" ");
```

Is this intended behavior? Working with crfsuite the labels are used "as is" which in my case means containing spaces. This generally results in an ArrayIndexOutOfBoundsException, though running with labels without spaces works just fine.

**Comment by daxenberger** [comment]
It's probably better not to set restrictions on the label strings. Thus, we need to make sure that either the relevant functionality in the Id2Outcome class is changed, or that label strings get escaped by default (and independent of the ML framework used). I'll have a look at this.

**Comment by daxenberger** [comment]
Should be fixed in 13158f4436fbf9a0185fc499e788b074c9db6ab2. Please verify

**Comment by Horsmann** [comment]
What is the status here? Looks fixed since 8 months without any comment from the issue creator. Can we close this one?

**Comment by daxenberger** [comment]
I guess so.
