### ISSUE TITLE
ClassificationUnitCasMultiplier does not set "isLastSegment" flag

### ISSUE THREAD

**Issue by mwunderlich** [dkpro/dkpro-tc#261]
The ClassificationUnitCasMultiplier is currently not setting the isLastSegment flag which is required for a second CAS multiplier to be able to merge the results of the multiplier step back into one CAS. 
For details on CAS merging see: 
https://uima.apache.org/downloads/releaseDocs/2.1.0-incubating/docs/html/tutorials_and_users_guides/tutorials_and_users_guides.html#ugr.tug.cm.using_cm_to_merge_cases

I think this is a bug, because the DocumentMetaData annotation has an attribute for this flag. 
Let me know, if this analysis is correct and I will commit a bug fix.

**Comment by daxenberger** [comment]
Sounds reasonable. I don't think there is any reason why this flag has not been set. Please go ahead.

**Comment by mwunderlich** [comment]
Done: 1bb68516aacc76953ed64460a52c359ba5b17dd4

Cheers, 

Martin
