### ISSUE TITLE
DKpro TC 0.8.0-SNAPSHOT  does not work with Lab 0.12.0-SNAPSHOT

### ISSUE THREAD

**Issue by mwunderlich** [dkpro/dkpro-tc#264]
There are some incompatilibities caused by the modifications to the BatchTask implementation. Most of the required fixes in TC are already done in this branch here: 

https://github.com/dkpro/dkpro-tc/tree/DKPro-Lab_Migration_to_0.12.0-SNAPSHOT_WIP

However, there are still failing unit tests in some of the examples, which needs to be looked into.

**Comment by mwunderlich** [comment]
Fixed by Richard.

**Comment by daxenberger** [comment]
There are a couple of things left - most tests are currently failing at runtime. I suspect this is related to DKPro Lab 0.12.0-SNAPHOT.

**Comment by daxenberger** [comment]
Ok, tests are passing now.
