### ISSUE TITLE
Potential MetaData error in ClassificationUnitCasMultiplier

### ISSUE THREAD

**Issue by mwunderlich** [dkpro/dkpro-tc#266]
When the processed CAS already contains an annotations for DocumentMetaData, the following will produce an error further downstream: 

``` java
public AbstractCas next()
        throws AnalysisEngineProcessException
    {
        // Create an empty CAS as a destination for a copy.
        JCas emptyJCas = this.getEmptyJCas();
        DocumentMetaData.create(emptyJCas);
...
```

This can lead to a situation where the CAS has two MetaData annotations, which leads to the following error: 
java.lang.IllegalArgumentException: java.lang.Throwable: CAS contains more than one de.tudarmstadt.ukp.dkpro.core.api.metadata.type.Document

So, there should be only one metaData annotation.

**Comment by daxenberger** [comment]
This could be avoided by a simple check if I am not mistaken.

**Comment by mwunderlich** [comment]
I have created a fix for this issue, based on the observed properties of the superfluous metadata annotation. It is a bit strange, though (both the bug and the fix).
