### ISSUE TITLE
Replace @author annotation in source by a contributors.txt file

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-tc#269]
This change is in line with best practice in DKPro Core and DKPro Lab.

**Comment by daxenberger** [comment]
Also, refer to contribution guidelines at https://dkpro.github.io site and DKPro Code Style file for Eclipse at http://dkpro.github.io/contributing/ (on GitHub pages).

**Comment by Horsmann** [comment]
Can I remove the author-tags in the source files then?

**Comment by daxenberger** [comment]
> Can I remove the author-tags in the source files then?

yes
