### ISSUE TITLE
DetailedOutcomeReport: Only one report is created for several test tasks

### ISSUE THREAD

**Issue by mwunderlich** [dkpro/dkpro-tc#271]
In an experimental setting with several Weka test tasks, such as a feature ablation experiment, only one detailed outcome report is generated. The detailed outcome report file resides in the Evaluation directory and possibly gets overwritten for each test task. There should be one report per test task, preferably referencing the test task by ID and maybe even including the features.

**Comment by reckart** [comment]
How can a report output be overwritten? Reports run only once and task context are not reused.

**Comment by mwunderlich** [comment]
Just a first hypothesis of what the cause might. Could very well be something else, as I haven't looked into it closely, yet.

**Comment by reckart** [comment]
If the "AccessMode" (readonly, readwrite, addonly) parameter is correctly specified on these methods 

```
File getStorageLocation(String aKey, AccessMode aMode);
File getFolder(String aKey, AccessMode aMode);
File getFile(String aKey, AccessMode aMode);
```

then DKPro Lab should take care of copying any imported data to the current context such that no data once written is ever changed after a task execuction is complete.

**Comment by mwunderlich** [comment]
I had a closer look now and I think the error is in the way the relevant test task is determined: 

``` java
for (TaskContextMetadata subcontext : getSubtasks()) {
            String type = subcontext.getType();
            if (type.contains(TEST_TASK_ID)) {
                try {
                    predictionsMap = store.retrieveBinary(subcontext.getId(),
                            Constants.ID_OUTCOME_KEY, new PropertiesAdapter()).getMap();
                }
                catch (Exception e) {
                    getContext().error("Error while trying to read predictions from test task file.", e);
                }
            ...
```

If there are more than one test task, this will only take into account the predictions from the last one in the loop. I'll get that fixed.
(in a comment in the above, I even noted at the time I wrote the code that this is a bad hack; what goes around, comes around)

**Comment by daxenberger** [comment]
At the Batch (=top/experiment) level, reports need to be aware that such kind of loops

``` java
for (TaskContextMetadata subcontext : getSubtasks()) {
            String type = subcontext.getType();
            if (type.contains(TEST_TASK_ID)) {
            ...
            }
}
```

potentially react to various tasks of the same kind (here: TestTasks).
See e.g. BatchTrainTestReport on how to deal with this.

The note about the bad hack is much older - now you know why this is not the optimal solution. We need a better way to refer to certain kinds of tasks here.

**Comment by mwunderlich** [comment]
Ah, yes, you're right. That wasn't even my comment about the bad hack. Phew. :)

**Comment by Horsmann** [comment]
Report in question does not exist anymore. Might have become obsolete.
