### ISSUE TITLE
NPE in number/string parsing in reports

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-tc#273]
In BatchCrossValidationReport, I am now seeing an NPE here:

```
                double[] dVals = new double[vals.length];
                Set<String> sVals = new HashSet<String>();
                for (int k = 0; k < vals.length; k++) {
                    try {
                        dVals[k] = Double.parseDouble(vals[k]);
                        sVals = null;
                    }
                    catch (NumberFormatException e) {
                        dVals = null;
                        sVals.add(vals[k]); // NPE
                    }
                }
```

This is because for the first value `0.0`, the sVals is set to null and for the second value `[]` parsing as a double fails.

```
vals = [0.0, []]
header = de.tudarmstadt.ukp.dkpro.tc.core.task.ExtractFeaturesTask|featureFilters
```

Any idea?

**Comment by daxenberger** [comment]
This happened because the values for the (empty) featureFilters dimension were "changed" after the first execution of the ExtractFeaturesTask. It is both a TC issue (the "default" value for this discriminator was set too late) as well as a Lab issue (which behaves a bit counter-intuitive here).

**Comment by daxenberger** [comment]
See also https://github.com/dkpro/dkpro-lab/issues/85.
