### ISSUE TITLE
Upgrade to meka 1.9.0

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-tc#276]
Meka 1.7.7 is now available from maven central.

**Comment by daxenberger** [comment]
meka 1.9.0 is a major release and fully mavenized.

**Comment by Horsmann** [comment]
@daxenberger Are you motivated to do the update in this snapshot iteration. Seems to be a bit more work than just exchanging library version numbers?

**Comment by daxenberger** [comment]
Definitely more than version numbers, but I'll have a look at this.

**Comment by daxenberger** [comment]
Was quite painfree. Closing.
