### ISSUE TITLE
Example for experiment over varying preprocessing

### ISSUE THREAD

**Issue by zesch** [dkpro/dkpro-tc#277]
After some discussion on the dev list (and offline with @reckart ), we decided not to make preprocessing a new dimension but to provide an example that changes preprocessing based on user defined dimensions such as "useStemming".

**Comment by reckart** [comment]
Looks ok - I have condense the code a bit.

In my opinion, there should be a getPreprocessing() method and the field should be private in ExperimentCrossValidation. Then I might not even override initialize() but directly getPreprocessing (well, right now there are various pros/cons and doing so would not be the best choice).

With the changes, I think preprocessing should be turned into an optional constructor parameter.

**Comment by daxenberger** [comment]
Richard's suggestion sounds reasonable to me. Unless anybody objects, we can introduce getPreprocessing() and make the constructor parameter optional.

**Comment by zesch** [comment]
+1

Preprocessing should be optional in a strict sense anyway :)

2015-09-15 15:14 GMT+02:00 Johannes Daxenberger notifications@github.com:

**Comment by Horsmann** [comment]
@daxenberger This one can be closed, too?

**Comment by daxenberger** [comment]
yes. this has been done without referring to the issue.
