### ISSUE TITLE
Remove Google Code build jobs on Jenkins

### ISSUE THREAD

**Issue by logological** [dkpro/dkpro-tc#278]
If/when they are no longer in use, please remove this project's Google Code build jobs on Jenkins:
- [DKPro Text Classification Framework (Google Code)](https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/DKPro%20Text%20Classification%20Framework%20%28Google%20Code%29/)
- [DKPro Text Classification Framework 0.3.x Branch (Google Code)](https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/DKPro%20Text%20Classification%20Framework%200.3.x%20Branch%20%28Google%20Code%29/)

**Comment by daxenberger** [comment]
Done.
