### ISSUE TITLE
Model saving/loading of SVMHMM models

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#282]
Making the next classifier available for the TC model storing/loading

**Comment by Horsmann** [comment]
In the SVMHMM module are many calls such as this one:

`File trainingDataStorage = aContext.getStorageLocation(TEST_TASK_INPUT_KEY_TRAINING_DATA,
                StorageService.AccessMode.READONLY);`

getStorageLocation() seems to be deprecated - which API call is the new one?

**Comment by Horsmann** [comment]
ToDo:
- The classification arguments need to be serialized, too
- Testing

**Comment by reckart** [comment]
As it says in the JavaDoc for `TaskContext.getStorageLocation(String, AccessMode)`:

```
     * @deprecated Use {@link #getFolder(String, AccessMode)} or {@link #getFile(String, AccessMode)}
```
