### ISSUE TITLE
Model Saving/Loading: Store TC version used for training

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#285]
Hi,
an open point for the model saving/loading is storing the TC version under which a model was trained. 

It is in general a good idea to be able to associate a model with a certain TC version. 

This would be helpful to point the user to potential problems in the version of TC used for training the model and the one that is used at the moment. For instance the recent API changes of the FE now returning Sets instead of List looked like a "bug", but was simply a changed API. This might happen in the future again.

What we need for such a version test is a place from where we can retrieve the version. Is there an API as `getCurrentVersionFromPom()`? Or any other location that reliably auto-updates when the POM-version is changed?

We then could simply write the version info into the model and compare the model version to the TC version. If they mismatch we simply print an warning.

**Comment by reckart** [comment]
Well, you can check for example how ResourceObjectProviderBase.getModelVersionFromMavenPom() works in principle. I'm sure there are other options as well.

**Comment by Horsmann** [comment]
Thx, I can read the version if I run the code from Eclipse, but reading the version from the jar to let it work with Jenkins is not yet working.

I skipped some of the code because I didn't know how to initialise it. This is probably why :). The method you link calls at the beginning: 

```
 // Get the properties and resolve the artifact coordinates
        Properties props = getAggregatedProperties();
        String modelArtifact = pph.replacePlaceholders(props.getProperty(ARTIFACT_ID), props);
        String modelGroup = pph.replacePlaceholders(props.getProperty(GROUP_ID), props);
´´´

The `getAggregatedProperties()` uses an `import` variable where I don't know how and with what I should initialise it?
```

**Comment by reckart** [comment]
I think getting artifactId / groupId is not relevant for your case - only the part that actually parses the POM should be relevant for you.

In order to locate the pom, you should probably use some method to find out the URL where your FE class was loaded from and then use it to construct a new URL that points to the typical location of the pom.xml. E.g if FE was loaded from JAR x, then the pom should also be in JAR x at a well-known location.

Cf. http://stackoverflow.com/questions/227486/find-where-java-class-is-loaded-from :

```
getClass().getProtectionDomain().getCodeSource().getLocation();
```

**Comment by Horsmann** [comment]
Is there a way to simulate the access if packed as jar? It works in Eclipse but fails on Jenkis.

Atm I try this and I get an error that the "URI is not hierarchical"

```
  pomUrl = contextClass.getProtectionDomain().getCodeSource().getLocation();
        File pomFile = new File(new File(URI.create(base)), "pom.xml");
        if (pomFile.exists()) {
            pomUrl = pomFile.toURI().toURL();
        }
´´´
```

**Comment by reckart** [comment]
Well, you cannot work with File. The URLs may not point to a location on the file system. You need to access the URL via a stream (https://docs.oracle.com/javase/tutorial/networking/urls/readingURL.html)

**Comment by Horsmann** [comment]
So I have to stream it and store it in a temporary location to process it further or would it be better to grab the <version> tag from the input stream?

**Comment by reckart** [comment]
Just stick with the stream. In general: stick with streams as long as you can and only materialize them as (temp) files if there is absolutely no other way.

**Comment by Horsmann** [comment]
It is still not working :(

The path that is used seems basically right, though.

```
de.tudarmstadt.ukp.dkpro.lab.engine.ExecutionException: de.tudarmstadt.ukp.dkpro.lab.engine.ExecutionException: java.io.FileNotFoundException: /home/svc_jenkins/workspace/DKPro Text Classification Framework (GitHub)/dkpro-tc-core/target/dkpro-tc-core-0.8/pom.xml (Datei oder Verzeichnis nicht gefunden)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileInputStream.<init>(FileInputStream.java:93)
    at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
    at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
    at java.net.URL.openStream(URL.java:1038)
    at de.tudarmstadt.ukp.dkpro.tc.core.util.SaveModelUtils.writeCurrentVersionOfDKProTC(SaveModelUtils.java:227)
```

My code looks like this atm:

```
        Class<?> contextClass = SaveModelUtils.class;

        URL pomUrl = null;

        pomUrl = contextClass.getProtectionDomain().getCodeSource().getLocation();
        String base = pomUrl.toString();
        base = base.substring(0, base.length() - "target/classes/".length());
        base += "/pom.xml";
        URI pomUri = URI.create(base);
        pomUrl = pomUri.toURL();


        String version=null;
        BufferedReader in = new BufferedReader(
                new InputStreamReader(pomUrl.openStream())); //here the exception occurs
                String inputLine;
                while ((inputLine = in.readLine()) != null){
                    if(inputLine.contains("<version>")){
                        version = inputLine.replaceAll("<version>", "").replaceAll("</version>", "").replaceAll("\t", "");
                        break;
                    }
                }
                in.close();
```

**Comment by reckart** [comment]
What does not work?

**Comment by Horsmann** [comment]
The pom.xml is not found (if run on jenkins - locally everything works)
/home/svc_jenkins/workspace/DKPro Text Classification Framework (GitHub)/dkpro-tc-core/target/dkpro-tc-core-0.8/pom.xml (Datei oder Verzeichnis nicht gefunden)

**Comment by reckart** [comment]
Depending on whether you run this in Eclipse or in a regular Maven build on the command line (or as part of an experiment) the POM is in a different place.

Cf. ResourceObjectProviderBase.getModelVersionFromMavenPom() line 3500ff

It is never in "target/pom.xml"

**Comment by reckart** [comment]
Btw. you also cannot rely on the order of "version" elements in the XML file. The first version in the file is not necessarily _the_ version - it can also be a dependency version for example. Using a proper XML (or POM) parser should be more robust.

**Comment by Horsmann** [comment]
Is there any way to debug that? Everything works locally and waiting for Jenkins to build lets me only now fail/success but never get a chance to see which part of the code is working.

**Comment by reckart** [comment]
Jenkins performs a build equivalent of a Maven command line build. On how to debug these, see e.g.
- https://doc.nuxeo.com/display/CORG/How+to+Debug+a+Test+Run+with+Maven
- http://maven.apache.org/surefire/maven-surefire-plugin/examples/debugging.html
