### ISSUE TITLE
CRFsuite: Add a train-test sub-class that automatically stores the model after the train/test run

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#286]
because it is convenient

**Comment by Horsmann** [comment]
The class `CRFSuiteModelSerializationDescription` performs explicit an own model-training call which leads to a double-training of the model which is exactly what this class is suppose to avoid...

**Comment by Horsmann** [comment]
This seems more difficult than expected. 

@daxenberger 
Maybe you have an idea / know how to...
If the ModelSerialization Task does not train the model itself it is unaware of the location of the serialised classifier. In a train/test situation the classifier is placed in the folder `CRFSuiteTestTask-*`.

I need to copy the file from there into the working folder of the current task.

When I am in another task (in the `CRFSuiteModelSerializationDescription` ) how can I access a file that was created in the folder `CRFSuiteTestTask-*`. ?

**Comment by daxenberger** [comment]
Do you refer to the batch task carried out by `de.tudarmstadt.ukp.dkpro.tc.crfsuite.task.serialization.SaveModelCRFSuiteTrainTestTask`? If so, you should be able to add a dependency from the model output of `CRFSuiteTestTask` to the input of `CRFSuiteModelSerializationDescription` (`saveModelTask.addImport(...)`) which makes the model available to the latter.

**Comment by Horsmann** [comment]
Yes, it is in the BatchTask. If I add the task as import do I have to do something additionally, I get an exception but I don't really get what it is trying to tell me.

```
   -Unable to resolve key [classifier.ser] of task [de.tudarmstadt.ukp.dkpro.tc.crfsuite.task.serialization.CRFSuiteModelSerializationDescription-BrownPosDemoCV_CRFSuite] pointing to [task-latest://de.tudarmstadt.ukp.dkpro.tc.crfsuite.task.CRFSuiteTestTask-BrownPosDemoCV_CRFSuite/classifier.ser]: Key not found; nested exception is de.tudarmstadt.ukp.dkpro.lab.storage.UnresolvedImportException:
```

I add as import the testTask defined in the super-class `ExperimentTrainTest` 

```
        saveModelTask.addImport(testTask, Constants.MODEL_CLASSIFIER);
        saveModelTask.trainModel(false);
```

**Comment by daxenberger** [comment]
As far as I can see, `CRFSuiteTestTask` (`testTask`) does not generate an output which could be accessed under the key `Constants.MODEL_CLASSIFIER`. See other tasks/dependencies how this should be done.
