### ISSUE TITLE
Introduce a single context-feature

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#292]
The features currently located at `de.tudarmstadt.ukp.dkpro.tc.features.tcu`(CurrentUnit, NextUnit, etc.)
should be replaced by a single-feature that is configured by a parameter.

i.e.
ContextUnit.PARAM_INDEX, 0 //refers to current token
ContextUnit.PARAM_INDEX, -1 //refers to previous token
ContextUnit.PARAM_INDEX, -5 //refers to the token 5 indices before

This would introduce a much a higher flexibility (allow using SkipNgrams, arbitrary long context windows, etc.)

This requires that the same feature can be used N-Times.
See issue: https://github.com/dkpro/dkpro-tc/issues/39

@daxenberger When will you merge the parametrization-fix into `master`?

**Comment by daxenberger** [comment]
> @daxenberger When will you merge the parametrization-fix into master?

I'll look into it in the next days.
