### ISSUE TITLE
CRFsuite: Prevent training-files from being deleted after training

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#294]
I noticed that CRFsuite deletes the training-files after training. 

First, I am not sure if this is a good idea sometimes you might want to take look into the actual input-file for training/testing. 
However, the training-files might become extremely big (several GB) if large training-data and ngram features are used. Crfsuite furthermore does not work with compressed files. Leaving them on the hard-disk will quickly eat up the disk-space and it might be difficult for the user to figure out why the free disk-space shrinks so quickly...

Second, I can't locate the code-line where the file-deletion is performed.

**Comment by daxenberger** [comment]
I recently discovered this and was wondering about exactly the same thing. Might indeed be related to the size of the file.

> Second, I can't locate the code-line where the file-deletion is performed. 

Should be this one: https://github.com/dkpro/dkpro-tc/blob/master/dkpro-tc-ml-crfsuite/src/main/java/de/tudarmstadt/ukp/dkpro/tc/crfsuite/writer/CRFSuiteDataWriter.java#L58

In conclusion: what is your suggestion? delete the file by default? or by choice of a parameter?

**Comment by Horsmann** [comment]
I think we should keep the files. All other classifier keep the files, too. It is confusing if CRFsuite behaves differently.

It would be possible to zip the file after CRFsuite used them, but this would lengthen the whole training-process to compress the train/test file even more and disk-space is the cheapest of all resources we have. 
If you intensively re-run an experiment you have to delete the DKPRO_HOME folder here and there.

**Comment by daxenberger** [comment]
> I think we should keep the files. All other classifier keep the files, too. It is confusing if CRFsuite behaves differently.

I agree.

**Comment by daxenberger** [comment]
fixed in 14c1afe53c828df7561f51c513c35cfb2c327bf9.
