### ISSUE TITLE
Setting NoOpAnnotator by default if no preprocessing is defined

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#295]
The preprocessing is still a must-set parameter in experiments. At least in my projects I have quite often the case that I do not need any because all information are read from the gold-training file.

To simplify the configuration of an experiment, we could always set the `NoOpAnnotator` in an experiment's constructor which would be overwritten if `setPreprocessingPipeline()` is called.

Are there any reason why setting NoOp as default is not a good idea?

**Comment by zesch** [comment]
I would at least add a warning about the empty preprocessing, as most people might simply forget to set it :)

**Comment by daxenberger** [comment]
yeah; warning seems reasonable

**Comment by Horsmann** [comment]
I just found this here in the superclass `Experiment_ImplBase`

```
 @Override
    public void initialize(TaskContext aContext)
    {
        super.initialize(aContext);

        try {
            if (getPreprocessing() == null) {
                preprocessing = AnalysisEngineFactory.createEngineDescription(NoOpAnnotator.class);
            }
        }
        catch (ResourceInitializationException e) {
            throw new RuntimeException(e);
        }

        init();
    }
```

Seems like this has been the intended default behaviour right from the start?

So it suffice to simply remove the null-check on the preprocessing variable. 

Another question, the the exception-text says:
 "You must set Experiment Name, DataWriter and Aggregate.");
This "dataWriter" is no longer an issue and can be removed it is automatically retrieved from the adapter description?!

**Comment by Horsmann** [comment]
Which logging framework is the one we are supposed to use? I used now `org.apache.commons.logging.Log`

**Comment by Horsmann** [comment]
Hm, Jenkins is failing what exactly is not working here? 
The tests seem not to be the problem
https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/DKPro%20Text%20Classification%20Framework%20(GitHub)/155/de.tudarmstadt.ukp.dkpro.tc$dkpro-tc-ml-weka/

**Comment by reckart** [comment]
Apache Commons Logging is a good choice. I would recommend that.

Unless you are writing a UIMA component, in which case you should simply call getLogger() whenever you need a logger - the uimaFIT base classes for UIMA components provide that method.

**Comment by reckart** [comment]
Search for ": error:" (colon space "error" colon) in the logs - that will take you to the JavaDoc errors. E.g.:

```
[ERROR] /home/svc_jenkins/workspace/DKPro Text Classification Framework (GitHub)/dkpro-tc-ml-weka/src/main/java/de/tudarmstadt/ukp/dkpro/tc/weka/task/serialization/SaveModelWekaBatchTask.java:77: error: exception not thrown: java.lang.ClassNotFoundException
[ERROR] * @throws ClassNotFoundException
```

**Comment by Horsmann** [comment]
It fails because of Java-Docs o.0?

**Comment by reckart** [comment]
Yes - since Java 8, JavaDocs are checked more strictly. IMHO that's a very good thing. In this case, it is because of wrong JavaDoc tags - but the build may also fail if HTML tags in the JavaDoc are malformed.

**Comment by Horsmann** [comment]
hm, ok. I removed the wrong tags. Lets see if it builds now.

**Comment by reckart** [comment]
If you run into JavaDoc problems, it is a good idea to test locally (and rather quickly) by running `mvn javadoc:aggregate` or `mvn javadoc:javadoc` in the project root.

**Comment by Horsmann** [comment]
okay, thx!

**Comment by daxenberger** [comment]
> Seems like this has been the intended default behaviour right from the start?
> So it suffice to simply remove the null-check on the preprocessing variable.

Yes :)

> Another question, the the exception-text says:
> "You must set Experiment Name, DataWriter and Aggregate.");
> This "dataWriter" is no longer an issue and can be removed it is automatically retrieved from the 
> adapter description?!

The javadoc was totally outdated, thanks for correcting.
