### ISSUE TITLE
Adding save-model TaskBase to TCMachineLearningAdapter

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#296]
The model-saving works since a few month. This feature should be usable like `ExperimentTestTask` or `ExperimentBatchTask` i.e. calling a more-generic 'ExperimentSaveModelTask'
At the moment you have to know the name of the respective ML-Adapter-Task e.g. `SaveModelCRFSuiteBatchTask` , `SaveModelWekaBatchTask` or `SaveModelSvmhmmBatchTask`

The TCMachineLearningAdapter should be extended by an interface definition such as 
`public TaskBase getSaveModelTask();`

ML-Adapter for which we do not have such a save-model task yet should then simply throw an UnsupportedOperationException.

**Comment by Horsmann** [comment]
1)
Meka is not the same as Weka? The WekaSaveModel adapter does not work for Meka? I set the SaveModelTask to Unsupoorted in the Meka-Adapter, is this correct?

2)
Is there a more beautiful way for this line:
https://github.com/dkpro/dkpro-tc/commit/ced5ffdba014632a62ae23943a6be685f13d5bac#diff-655c713fd814ecd4cb7a43a4528dd9b0R105

3) `WekaTestTask_ImplBase` inherits now from `ModelSerializationTask` maybe not the most beautiful solution either

**Comment by Horsmann** [comment]
@daxenberger 
The unit test which tests an "empty cas" in `de.tudarmstadt.ukp.dkpro.tc.core.io.ClassificationUnitCasMultiplierTest`fails now. I am not sure how my recent change is connected to this test failure. Any ideas?

**Comment by daxenberger** [comment]
> The unit test which tests an "empty cas" in 
> de.tudarmstadt.ukp.dkpro.tc.core.io.ClassificationUnitCasMultiplierTestfails now. I am not sure how 
> my recent change is connected to this test failure. Any ideas?

The test doesn't fail - is is expected to throw an exception. The problem is a license problem (GPL instead of ASL in ModelSerializationTask).

**Comment by daxenberger** [comment]
> Meka is not the same as Weka? The WekaSaveModel adapter does not work for Meka? 
> I set the SaveModelTask to Unsupoorted in the Meka-Adapter, is this correct?

Meka extends Weka to allow for multi-label classification. It uses it's own DataWriter as the ARFF format is slightly different to Weka-only.
AFAIK everything else is the same - so I guess the SaveModelTask would also work with Meka.

> WekaTestTask_ImplBase inherits now from ModelSerializationTask maybe not the most 
> beautiful solution either

Hmm yeah, I'd rather see them separated...

**Comment by Horsmann** [comment]
The two methods of `WekaTestTask_ImplBase` (`protected Classifier getClassifier()` and `protected void featureSelection(TaskContext aContext, Instances trainData)`) should become static and move to `WekaUtils`.

We would have to extend the parameter list as they use variables that are made available by `@Discriminator` annotations, but it looks like we could delete the whole class?

**Comment by daxenberger** [comment]
Why would you want to move them to a utility class if classes which need those methods could inherit from `WekaTestTask_ImplBase`?

**Comment by Horsmann** [comment]
Storing the model in `WekaModelSerializationDescription` needs `getClassifier()` which is why I chose this unpretty inheritance of WekaTestTask extending the `ModelSerializationTask`. 
I can leave the class as is but will then have to produce code redundancy to provide the getClassifer() method if I want to resolve the current inheritance.

**Comment by daxenberger** [comment]
Ok, I see.
Probably the original proposal is the best way to go here (move redundant methods to utility and extend parameter list) - at least it is what we have done in the past.

**Comment by Horsmann** [comment]
Weka inheritance hierarchy is fixed now, too.
