### ISSUE TITLE
Create combined id2outcome.txt to experiment folder in CV setting

### ISSUE THREAD

**Issue by zesch** [dkpro/dkpro-tc#297]
In the cross-validation setting it would be good if the evaluation report would also combine all id2outcome files and write that to the batch experiment folder.

**Comment by zesch** [comment]
We have that already (BatchOutcomeIdReport).
If the author tag is right, I wrote that ;)

**Comment by reckart** [comment]
Follow the path of the author tag you should not. The wisdom of the history consult you should.

**Comment by zesch** [comment]
History seems to be disrupted since we moved from DC to Marv ... ehm GC to GH

**Comment by reckart** [comment]
Indeed, something went pear-shaped during the migration... no idea why :( History should have been fully preserved. However, the file can actually be found in older revisions in the git repo, but the provenance chain somehow got interrupted.
