### ISSUE TITLE
FeatureMode and LearningMode are hardcoded in TCAnnotatorDocument

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-tc#303]
This is a problem for any experiment which non-document or non-singlelabel. Ideally, we should read those parameters from the saved model (as any parameters) - or at least allow setting them as ConfigurationParameters. Having separate Annotators for each mode is not necessary as far as I can see.
@Horsmann What do you think about this?

**Comment by Horsmann** [comment]
Sure, we just can write these parameters to the model as all the other information. 

> Having separate Annotators for each mode is not necessary as far as I can see.

There are some differences if I recall correctly: 
- Unit classification for instance does not allow to have several outcome annotations at the same time, so we have to set these for each unit we want to classify and delete them again before the next iteration starts.
- Sequence classification needs the sequence annotation but is ok with several outcome annotations.
- Document classification is the most simple case :)

Especially the unit annotator prevents the usage of a single class atm. It is a bit too restrictive with requesting exactly one outcome and one focus. To avoid this and become able to use a single annotator we would have to move the logic for iterating all "units" into the respective LoadModel\* of the individual ML-Adapters.

**Comment by daxenberger** [comment]
ok I see. wouldn't it be possible to use a single class (`TCAnnotator`) which operates differently with respect to the outcome annotations, given the feature/learning mode (which in turn could be retrieved from the stored model)?

**Comment by Horsmann** [comment]
Yes, this should work. 
I think we made separate classes because we did not know how similar the individual modes would be, but they do seem similar enough to merge them into one class.

**Comment by daxenberger** [comment]
Another, related issue:
this annotator only work for single-label learning (it assumes unique Outcome annotations). here again the question would be whether we include everything into a single class or individual ones.

**Comment by Horsmann** [comment]
I think we should add it then into the new TcAnnotator class, too. If it gets too much code for a single class we can outsource some code into a new util class.

At the moment only Meka is mutlilabel i.e. document-multilabel or is there unit-multilabel, too?
The main difference is the number of outcomes that can vary?

**Comment by daxenberger** [comment]
The learning mode (e.g. multi-label) is independent from the feature mode, i.e. we have multi-label for document, unit, pair etc. For multi-label, the main difference is that there can be more than one outcome annotation (per document/unit etc.).

**Comment by Horsmann** [comment]
Okay, I would tackle the multi-label problem in an own issue and add save/load of the two parameters and merging the current annotators into one in this one.

**Comment by daxenberger** [comment]
I can take care of the learning mode. 
@Horsmann Do I see correctly that you are going to tackle the feature mode?

**Comment by Horsmann** [comment]
My commits should cover the loading/storing of the 2 parameters to/from file and merged the 3 annotators into one.
If Jenkins builds we can close this issue and you could tackle the `learning mode` enhancement.

**Comment by Horsmann** [comment]
I also reorganised the code a bit, we had 3 util classes in different projects which all did some save model   tasks. Now there is only one `SaveModelUtils`

**Comment by Horsmann** [comment]
@daxenberger My changes are done and Jenkins builds again, too

**Comment by daxenberger** [comment]
alright; I'll take care of the learning mode then.

**Comment by daxenberger** [comment]
This is should be resolved.
