### ISSUE TITLE
Save and Load Weka Model doesn't work

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-tc#311]
Has anybody ever tried this? The relevant code snippet in WekaModelSerializationDescription only stores feature names from the model (not the Instance) which results in "a_1", "a_2" etc. 
This cannot work with the utilities that are used to load and apply the model later on.

**Comment by zesch** [comment]
This used to work, but has probably not keeping up with the latest changes in model serialization.
@Horsmann Can you have a look, please?

**Comment by Horsmann** [comment]
Ohm I cannot follow. I am not that familiar with Weka. What exactly is the problem, information is not serialized? When would we need this information, the Weka test do pass?

**Comment by daxenberger** [comment]
I can't see a test that would assert the issue.

The problem here is that the feature names are serialized _after_ the model is trained (the latter apparently modifies the Instances object so that the feature names are not kept). I don't know what might have changed here, but I wonder why it has ever been working...

**Comment by daxenberger** [comment]
There is another problem, as all attributes are recorded as "numeric" when they are loaded after serialization. String and nominal (and in theory, boolean) features are not recognized as such.

**Comment by daxenberger** [comment]
The feature name issue might occur in multi-label setups only, maybe that's why it hasn't occurred before.
I've added a demo which seems to work, but I'm still having issues with more complex setups. Leaving this open until investigated completely.

**Comment by daxenberger** [comment]
This is solved to the largest extent.
TODO: feature selection is not supported at the moment

**Comment by daxenberger** [comment]
will tackle remaining TODO in an own issue.
