### ISSUE TITLE
CrfSuite code clean up

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#312]
I think there are quite a few things that can be made a bit prettier in the CrfSuite module. 

For instance the inconsistent use of property files vs string builder + file utils. 

I will use this issue for tracking my clean up / changes.

**Comment by Horsmann** [comment]
@daxenberger in `CRFSuiteClassificationReport` is a comment that this class is a mock - is this still up to date?

**Comment by daxenberger** [comment]
This is not my comment, but I guess the report is this in mockup stage, it doesn't do anything...
The evaluation module can be used, however, in conjunction with the id2outcome report, so I doubt that this report is actually needed.

**Comment by Horsmann** [comment]
The output/evaluation.txt is no longer created. Instead the `CRFSuiteClassificationReport` creates the result.txt now which contains the correct/incorrect count and an accuracy value. 

I think it is ok to let a ML adapter at least print something like an accuracy file, more details and verbose information are then created by the evaluation module.

**Comment by Horsmann** [comment]
@daxenberger Are there any rules which decide when the `output` folder is used in the `CRFSuiteTestTask-` folder (or all other ML adapter's folder)?
In case of CRF the id2outcome lies in the top-level while the predictions.txt and the Sysout of the CRF binary are placed in the output folder.
I tend to remove the `output` folder entirely for CRF and just place everything top level.

**Comment by reckart** [comment]
I would recommend to use the DkproTestContext class to manage test outputs:

```
    @Rule
    public DkproTestContext testContext = new DkproTestContext();

    File output = textContext.getTestOutputFolder();
```

Mind that textContext.getTestOutputFolder() must only be called once per test because it cleans the folder every time it is called.

**Comment by daxenberger** [comment]
> Are there any rules which decide when the output folder is used in the CRFSuiteTestTask- folder (or all other ML adapter's folder)?

No explicit rules. I think is rather is a legacy issue. You just need to make sure that subsequent or higher level reports are aware of this (i.e. some of the reports in higher BatchTasks - CV and TrainTest - might break if you put everything at top level).
