### ISSUE TITLE
Switch to new DKPro Lab 0.12.0-SNAPSHOT artifacts

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-tc#319]
The groupId and package names in DKPro Lab 0.12.0-SNAPSHOT have been changed as part of preparing the upcoming release.
- New groupId: `org.dkpro.lab`
- New package prefix: `org.dkpro.lab`

It should be possible to migrate doing a global search/replace action from `de.tudarmstadt.ukp.dkpro.lab` -> `org.dkpro.lab`.

**Comment by Horsmann** [comment]
@reckart Groovy doesn't like org.dkpro the imports are not resolvable 

An idea what could cause this?

```
kpro/tc/groovyexamples/single/document/TwentyNewsgroupsDemoExtended.groovy (at line 33)
    import org.dkpro.lab.task.impl.DefaultBatchTask
                                   ^^^^^^^^^^^^^^^^
Groovy:unable to resolve class org.dkpro.lab.task.impl.DefaultBatchTask
```

**Comment by reckart** [comment]
Did you switch the dependencies to the new groupId?

**Comment by Horsmann** [comment]
Yes all other tc modules work fine its just the Groovy example project that causes problems.
I also have some plugin lifecycle issues with this project 

```
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (execution: default-testCompile, phase: test-compile)
```

related?

**Comment by reckart** [comment]
I don't think so.

There were still various references to the old groupIDs - I have updated them (see commit above).

**Comment by Horsmann** [comment]
strange, why did I miss them o.0 ... thanks
it builds now
