### ISSUE TITLE
MLA-ClassificationReports and Batch*Reports

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#320]
I think we have a little file redundancy in TC. 
There is a `Constants.RESULTS_FILENAME` and the `evaluationFile` defined in the machine learning adapter projects (i.e. `evaluation.txt`).

The `*ClassificationReport` class in the different MLA create either of them or both and it does not look like there is a fixed formatting for the file content either.

The file `Constants.RESULTS_FILENAME` is expected to exist by the `BatchTrainTestReport`

My naive suggestion would be to remove the `Constants.RESULTS_FILENAME`from all reports and use the `evaluationFile` file of the MLA instead. 

@daxenberger Do you remember for which purposes these 2 files were created originally?

**Comment by Horsmann** [comment]
In case of the MLA this is easy to change. The only thing that I cannot resolve are the `BatchTrainTestReport` and `BatchTrainTestLatexReport` - how do I get the machine learning adapter in the generic BatchReport from the context object?

**Comment by Horsmann** [comment]
@reckart If I am in a BatchTrainTestReport and not in any MLA specific code - how can I retrieve the machine learning adapter from the context object I have?

**Comment by Horsmann** [comment]
Ok - I think this file redundancy stems from using Weka as `template` for the other adapter.

For `liblinear`, `svmhmm` and `crfsuite` the evaluation file as defined over the framework constant `evaluationFile` and the `results.txt` defined by the `Constants.RESULTS_FILENAME` which is created in the `ClassificationOutcomeReport` are essentially the same information.

@daxenberger Can I delete the evaluationFile constant from the machine learning adapters. The need for this value seems to be Weka specific - I would leave the Weka module as it is and just remove the variable from the other MLA.

**Comment by reckart** [comment]
@Horsmann no idea - maybe the class name of the MLA is stored in the discriminators file? - otherwise maybe @daxenberger has an idea.

**Comment by daxenberger** [comment]
We have a couple of legacy issues here, plus some left-overs from Issue #50 and in particular #113.

>  Can I delete the evaluationFile constant from the machine learning adapters. The need for this value seems to be Weka specific - I would leave the Weka module as it is and just remove the variable from the other MLA.

Yes.

Furthermore, after the full switch to the new evaluation mode, the only thing that each TestTask need to produce should be an Id2Outcome file with the usual content. With the Evaluation module it should then be possible to use this file to calculate the desired scores (which are then collected and further processed/aggregated by `BatchTrainTestReport`, `BatchTrainTestLatexReport` etc.).

**Comment by Horsmann** [comment]
Ok, since changing this effects all MLA and might have too many unknown side-effects I push this to `0.9.0`

**Comment by Horsmann** [comment]
I removed the `evaluation` file from the interface. The results written by the reports are now written into the file named `Constants.RESULT_FILE`
