### ISSUE TITLE
Update package names to org.dkpro.tc

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#321]
Replace the group id of the TC projects `de.tudarmstadt.ukp.dkpro.tc` with `org.dkpro.tc`

**Comment by Horsmann** [comment]
@reckart could you please put the `Crfsuite` and `liblinear` binaries into artifactory

**Comment by reckart** [comment]
@Horsmann not sure what you mean. liblinear is on Maven Central and should be used from there - and it is a Java library, so no binary, right? Which crfsuite binary?

**Comment by Horsmann** [comment]
oh, I meant `svmhmm` then. The binaries had the old package path which I also updated. The `de.tudarmstadt*` binaries are not found anymore.
I updated the ant-installation scripts of the binaries accordingly

**Comment by Horsmann** [comment]
@reckart  I mean the maven artifacts we created for the binaries of `crfsuite` and `svmhmm` that are created by executing the ant-scripts.

e.g.
`de.tudarmstadt.ukp.dkpro.tc.crfsuite-bin` -->  `org.dkpro.tc.crfsuite-bin`

**Comment by reckart** [comment]
Both deployed to artifactory.

**Comment by Horsmann** [comment]
Into the right repository?
There is no `tc` folder under `org.dkpro`
http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-ukp-snapshots-local/org/dkpro/

**Comment by Horsmann** [comment]
Never mind, TC builds again.
