### ISSUE TITLE
Update Weka Multilabel test case

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#323]
When updating the group id to `org.dkpro.tc` a Weka multi label test case had to be set to `@Ignored` which uses a bin file that has the old group id in it and lets the test fail with a ClassNotFoundException.

I don't know how to recreate a new bin file so I ignored it temporarily. 

It is the test case `testGenerateOutcomeIdPropertiesMultiLabel`, see below commit for the test case
https://github.com/dkpro/dkpro-tc/commit/97da66487b14a9fd2dd3f22b9fd623be20954670

**Comment by Horsmann** [comment]
I tried to edit the .bin file and simply update the text string, but it breaks if you do that. If possible recreate the .bin file with the latest tc version.

**Comment by daxenberger** [comment]
Fixed.
