### ISSUE TITLE
Example Project: Prefixing examples with the MLA name that is used

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#326]
Hi,

how about we rename the examples in the `example` project and use the MLA name as prefix (rather than as suffix how it is atm _sometimes_ the case)

If you are new to TC you either know the kind of task you want to perform (e.g. document, unit, sequence) or you know already that you will have to use a certain MLA (i.e. most familiar to it). 
For the former case the `package` naming provides sufficient evidence where to look. 

For the latter case you start clicking through all packages at the moment and looking into the class files. Some classes have as suffix the name of the MLA they are using, but this is hard to notice. I would suggest to prefix each file with the MLA 

would look like this:
`MekaComplexConfigurationMultiDemo`
`MekaReutersUsingTCEvaluationDemo`
`MekaSaveAndApplyModelMultilabelDemo`

A positive side effect for newbies to TC would be that they automatically learn which MLA supports which modes. Are there any objections to prefixing ( @daxenberger ?)

**Comment by daxenberger** [comment]
Sounds good; No objections
