### ISSUE TITLE
SvmHmm: SVMHMMOutcomeIDReport crashes if feature is missing

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#327]
The `SVMHMMOutcomeIDReport` crashes if a certain feature is not provided: `OriginalTextHolderFeatureExtractor`

I am not sure if this is even fixable as some information seems to be carried through the whole process with this feature. At least a more meaningful exception should be thrown to point the user to the necessity of this feature

**Comment by Horsmann** [comment]
A more meaningful exception is thrown now still needs investigation if using this feature is avoidable.

**Comment by Horsmann** [comment]
@reckart Is there a way to hack-in another information into an already created dimension? I would want to secretly add a feature in the background which his needed by a particular classifier.

**Comment by zesch** [comment]
I think there is no need to hack the dimension. The SvmHMM data writer should simply make sure that the required feature is present.

**Comment by Horsmann** [comment]
The feature carries the token-text through the process. I need it to be `there` when the FE are executed

```
   @Override public Set<Feature> extract(JCas jCas, TextClassificationTarget textClassificationUnit)
            throws TextClassificationException
    {
        return new Feature(ORIGINAL_TEXT, textClassificationUnit.getCoveredText()).asSet();
    }
```

**Comment by zesch** [comment]
ok, this feature extractor definitely has to run with the others.
However, in a context where you want to hack the dimensions, it is probably too late anyway.
Can't we just throw an exception if the feature is not present for SvmHMM and ask the user to add this FE?

**Comment by reckart** [comment]
> @reckart Is there a way to hack-in another information into an already created dimension?

Given that DKPro Lab doesn't create an execution plan, you probably could try doing something like that. But I don't think I would recommend it and there is no official provision for doing so.
