### ISSUE TITLE
Update to DKPro Lab 0.12.0 (release)

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#328]
Update to release version as soon as it is available.

**Comment by Horsmann** [comment]
@reckart is there anything left that blocks a release?

**Comment by reckart** [comment]
Not strictly. @maxxkia has updated some dependencies in preparation of the release which need to be double checked (https://github.com/dkpro/dkpro-lab/issues/92#issuecomment-206238834).
