### ISSUE TITLE
Add new window features

### ISSUE THREAD

**Issue by betoboullosa** [dkpro/dkpro-tc#329]
Add new window features: Case, CoveredLowerText, CoveredText, LemmaText, POS, WordShape.

**Comment by betoboullosa** [comment]
@Horsmann , I didn't understand why you made the same commit twice (for adding the licence headers). Were the changes made in the first commit lost in between?

**Comment by Horsmann** [comment]
@betoboullosa Yes, I messed around and rolled the commit back where I lost this change. :)

**Comment by betoboullosa** [comment]
No problem, sometimes that happens.  :)

**Comment by Horsmann** [comment]
Is here anything left to do? Otherwise I would close this one. The classes would be included in the 0.8.0 release - I haven't branched yet.

**Comment by betoboullosa** [comment]
Closing.

**Comment by reckart** [comment]
Commits can still be easily "cherry-picked" from the master branch into the release branch later - unless master undergoes major refactorings.
