### ISSUE TITLE
SaveModel Weka Unitmode: fails with wrong number of outcome annotation

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#333]
In `LoadModelConnectorWeka` is a bug for `unit` mode processing when `getOutcomeForFocus` is called.

The issue seems to be the Iterator call 

```
Iterator<TextClassificationOutcome> outcomeIterator = JCasUtil
                .iterator(focus, TextClassificationOutcome.class,
                        false /* ambiguous */, false /* strict */);
```

This call returns nothing when the focus annotation and the TCO have perfect overlap (begin/end) position. The documentation says it returns a sub-iterator. 
I replaced this by a list.

I additionally add a new Unit test that runs model save/load for Weka in Unit mode

**Comment by Horsmann** [comment]
@daxenberger is it much effort for you to add a multi label model save/store round trip demo? We have now `document` and `unit`

**Comment by daxenberger** [comment]
> is it much effort for you to add a multi label model save/store round trip demo? We have now document and unit

I don't think so. I actually thought we already have that.

**Comment by daxenberger** [comment]
Well ok, we have `org.dkpro.tc.examples.multi.document.MekaWekaSaveAndApplyModelMultilabelDemo`

But I can add an explicit round-trip test for that as well.

**Comment by Horsmann** [comment]
Oh ok. I didn't see this one. Yes, if you can add it there. Then all 3 use cases are found in one place. Thx!

**Comment by daxenberger** [comment]
I've added tests for pair feature mode setups, as well as regression and multi-label learning modes.
