### ISSUE TITLE
Unit Classification: MetaCollector compute redundantly the ngram distribution

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#336]
When using NGram feature extractors in `unit` mode the meta collectors recreate the ngram distribution for each unit annotation.

This is first and foremost a runtime issue. Depending on the number of units the collection process might take ages to finish even for smaller data sets.

As a temporare solution we choke off the meta collectors. See details in the discussion on the mailing list: https://groups.google.com/forum/#!topic/dkpro-tc-dev/Lz04TiEVl4M

**Comment by Horsmann** [comment]
@daxenberger Seems to work any suggestions for improvements? This is as minimalistic as possible.

**Comment by daxenberger** [comment]
I've run a couple of small tests; it seems to work. 
Not the cleanest solution, but should do the job until we rewrite the entire CasMultiplier thing.
