### ISSUE TITLE
Improve DKPro-TC preprocessing speed by removing CasMultiplier from Workflow

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#341]
As discussed in greater detail here: https://groups.google.com/forum/#!topic/dkpro-tc-dev/tG1g-O7ZY_0

The I/O intensive preprocessing step in the `InitTask` and the many copied CAS objects needs to be refactored / removed by a much more performant solution.

Outline:
- [x] create branch `issue341`
- [x] Remove InitTask CAS Multiplying 
- [x] MetaTask remove changes of issue #336 
- [x] ExtractFeatureTask/ExtractFeaturesConnector - in-memory iteration over TextClassificationUnits
- [x] Unit & Sequence splitting removed
- [x] Numbering / creation of instance id in sequence/unit mode
- [x] Crossvalidation - TC needs to provide an method of creating and managing folds
  - [x] UNIT: splitting CAS into fitting folds if provided input files are too few to match `NUM_FOLDS` 
  - [x] SEQUENCE: treating sequences separately e.g. fold creation over sequences if sequences mode
  - [x] Add `manual fold` mode switch
- [x] Removing of the TextClassificationFocus annotation

**Comment by Horsmann** [comment]
Status update
Changes are straight forward except for the CV part.
- If as many documents are created as NUM_FOLDs are defined everything works
- If less documents are available than NUM_FOLDS an exception occurs
- No test case captures this bug

**Comment by Horsmann** [comment]
@daxenberger @zesch Solving the CV issue

As first solution for the problem I though we can call the CAS Multiplier if NUM_FOLDS is bigger than the number of documents found and generate more CAS objects so to say. This would essentially create the large runtime we have right now just later as optional scenario.
I think as first version this would be ok - It seems that the Cas Multiplier has some subtle behaviour issues? If you look into the commit above this post I added a pipeline where I try to call the multiplier in the `FoldUtil` class. The multiplier is called, but the created CAS clones do not reach the binCas writer. The BinCarsWriter writes only the original CAS objects which does not make much sense. What is the trick to make the Writer write the newly created CAS objects?

**Comment by Horsmann** [comment]
@daxenberger @zesch @reckart 
What kind of strategy would you recommend if we run into the case that we have less JCas than Num-folds?

We can do a more reasonable splitting than creating a CAS for each TCU. I would suggest we split each CAS in half. Thus one half of the TCUs is placed in one CAS the other half into the second CAS. Basically a less aggressive splitting than giving each TCU an own CAS. This seems still less expensive in terms of CPU time? Thought on this?

**Comment by zesch** [comment]
This strategy would e.g. fail if there only is one document and 10 folds are requested.
So if we have m CASes and k fold are requested with m<k, we would have to split in at least x parts so that x*m > k.

**Comment by Horsmann** [comment]
I will compute the multiplication factor needed to reach NUM_FOLDS and try to split each document accordingly. This will give rise to much more CAS that we need, but it still cheaper than single-TCU-in-a-doc. In case we have less TCU I will have to throw an exception anyway.

**Comment by Horsmann** [comment]
Are there any objections if we use the full filename for the feature id? The numeric suffix we used until now is gone because we no longer run through the `multiplier` looks like that atm:

```
_6_224_Umwelt=0;0
_9_424_Fachleute=36;0
_1_540_vielen=14;14
_7_348_1700=36;19
_4_96_2009=15;19
```

**Comment by Horsmann** [comment]
merged into master

**Comment by Horsmann** [comment]
`Document` mode requires now an `TextclassificationUnit` i.e. I had to replace the `focus` with something and I just add an `TCU` anno for the later processing steps to work.

We could think about renaming `TextClassificationUnit/Sequence` to `TextClassificationTarget` and call the sequence one `TextClassificationSequenceTarget` - it resolves a bit the confusion why a document has a unit.
@daxenberger @zesch opinions on renaming the annotations or leave them as they are?

**Comment by daxenberger** [comment]
I opt for renaming. The unit/sequence modes have caused confusion in the past; and a new name would help to reflect the rather deep modifications that have been introduced now.

**Comment by zesch** [comment]
Not so fast :)

In the core, the document has no unit.
If that is somehow necessary for the model loading/saving functionality (which might make the code nicer but more complicated to understand IMO), that is a completely other issue.

If I understand the proposal correctly, TCU would be renamed to TCT. We still need TCS to reflect that multiple TCU/TCTs are in one sequence.
I don't see how this improves anything.

**Comment by reckart** [comment]
Why is it necessary at all to make a difference between "single units" and "sequence units"?

**Comment by zesch** [comment]
Units are points in a document where the classifier should make a decision.
Sequences are (well) sequences of units that should be treated together when making a decision for each unit.

**Comment by reckart** [comment]
Sure, but does that change the nature of the unit itself? The only difference I see right now is that in document-classification-mode, there is one unit and in sequence-classification-mode, there are multiple units... but the units are essentially still units. They don't turn into apples in once case and potatoes in the other case.

**Comment by zesch** [comment]
In principle yes, but - a bit in contrast to what Tobias has written above - we actually do not have a unit in document mode at all.
The whole document is implicitly treated as a unit.
We could make that explicit and treat the document mode as a special case of unit classification with the whole document as one unit.
In that way, we might even get rid of the DFE/UFE distinction :)
However, that is a somewhat different discussion from the purely technical one above.

**Comment by Horsmann** [comment]
We will leave the annotation then as they are. I merged the JCasID annotation fix. I additionally added more test cases and fixed mostly self-introduced bugs ~ I think this can be closed then rather soon unless someone unhappy with any of the changes.
