### ISSUE TITLE
Groovy-Example: Delete test-cases / data to lower runtime

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#342]
The Groovy example project takes quite long to run. We already cleaned up the example Java project some time ago. The Groovy example should be similarity stripped down to ease development by getting quicker feedback from Jenkins about success/failure of builds.

@daxenberger @reckart  Are there any publication linked experiments in the Groovy project which I should not touch (data wise)

**Comment by Horsmann** [comment]
Or more precisely - I left the experiments in the Java project which correspond to a publication already untouched - the one in the Groovy experiment seem to be the same - thus I can delete some of the data in the Groovy project?

**Comment by daxenberger** [comment]
Please do not change `TwitterSentimentDemo`. This is linked to a publication.

**Comment by Horsmann** [comment]
can i take out the CV mode? I think TrainTest is enough? And this demo exist in CV in the Java version.

**Comment by daxenberger** [comment]
ok

**Comment by Horsmann** [comment]
@daxenberger do you know how this Reuter Demo works. There is a lot of data in it but I don't get what I can delete and what not

**Comment by daxenberger** [comment]
> do you know how this Reuter Demo works. There is a lot of data in it but I don't get what I can delete and was not 

Please keep that data. It's a moderate number of files and already at the minimum of what makes sense in a multi-label classification setup

**Comment by Horsmann** [comment]
Ok, the `PairTwentyNewsgroupsDemo.groovy` demo is similarity difficult to change. it easily breaks. Which properties does those `parilist` need to have? 

Its a pain to use groovy I have to `mvn build` the entire project every time I change something.

**Comment by Horsmann** [comment]
@daxenberger I don't know how important the support of Groovy is to you - but is it necessary that bigger demos such as the Reuter Demo and the Sentiment Demo exist also as Groovy version? Isn't the Java version enough?

**Comment by daxenberger** [comment]
I think we have some demos which are only tested in the groovy module. As long as we at least one test which checks the groovy setup in general,, we don't need to have a test for each configuration/setup in both groovy and java. But please make sure that if you delete a groovy test case, the same test exists in java.

**Comment by Horsmann** [comment]
This should do it for the moment

**Comment by daxenberger** [comment]
I think that was a bit too rigorous. At least, we should re-name the ComplexConfigDemo to reflect that it uses the Reuters demo... or better: keep the demo and just delete the test case.

**Comment by Horsmann** [comment]
ups right - i will delete the tests cases only then - i restored the data

**Comment by EmilyKJamison** [comment]
Hi Tobias,

PairTwentyNewsgroupsDemo.groovy demo: Are you getting rid of all Groovy
Demos which have a Java Demo counterpart?  PairTwentyNewsgroupsDemo.groovy
and PairTwentyNewsgroupsDemo.java do show the same thing, so they are
redundant, but it was a previous documentation design decision in TC, that
we created redundant demos rather than thoroughly document instructions for
the user.  A benefit of this approach was that it actually forced the
"documentation" to always be up-to-date, because otherwise the demo tests
would fail; other forms of documentation would not be so current.  (And
when TC had demos without tests, the demos were often broken for months
without anyone noticing.)

-Emily

**Comment by reckart** [comment]
You need to have the Eclipse Groovy plugins installed. The Groovy stuff
should work just as nicely from within Eclipse as it does in a Maven build.

I don't know why you believe you have to rebuild on the command line for
the Groovy things.

**Comment by Horsmann** [comment]
@daxenberger I commented out some tests which I found to be not necessary because redundant or too similar to other test cases. This involves mainly the bigger tests-cases. 
Runtime of the Groovy project is down to 2 min from 6 min in this configuration (my local computer). This would satisfy me :o

@EmilyKJamison The demo runtime is an obstacle for speedy development (i.e. waiting for Jenkins feedback) and I just try to sort out what is not really necessary to speed things up. Furthermore the Groovy project took quite a bit longer to build then the Java project.

**Comment by reckart** [comment]
@Horsmann it is absolutely possible to move tests to profiles such that they are only run on a separate build. Also, if you wait for Jenkins feedback, I'd say you do something a bit wrong. Changes should be tested before committing and the feedback from Jenkins should only be a secondary check, not the primary check.

Regarding different levels of testing, see e.g.
- https://technicaltesting.wordpress.com/2012/09/24/using-junit-category-and-maven-profiles-to-get-stable-test-suites/
- http://stackoverflow.com/questions/3100924/how-to-run-junit-tests-by-category-in-maven

**Comment by Horsmann** [comment]
@reckart Doesn't really matter I would say. To really make a complete test of the module you have to run the examples. The few test cases in the ML-adapter projects often succeed because they only test a small fraction of the project or the main error source lies outside the scope of an adapter and show only up if you run an entire pipeline. The example project is the only reliable instance for evaluation which of course has many redundancy with starting always an entire pipeline with CV and TrainTest. I just tried to get rid of what is not really needed. We should tackle the test cases of the ML-adapters in the near future too - similarly for the many feature extractors (for which we already have an issue). If you run the examples locally or on Jenkins is then not so much of a difference anymore.
