### ISSUE TITLE
CRFSuite: Use streaming mode 

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#347]
CRFSuite can read from `STDIN` for loading the `training` data or the `raw` data that is to be tagged.

This is helpful to speed up the use of an already trained model. Training the model has to keep using the HDD I/O method we use at the moment. The training data files might become huge and keeping them in-memory will make training a model even more memory demanding i.e. at one point we would have the entire feature store + its representation as String in memory. This will not scale.

**Comment by Horsmann** [comment]
This enhancement shows some serious speed gains on huge collections of text with many thousands sequences in it. On short ones it barely shows any effect.

**Comment by reckart** [comment]
@Horsmann observations regarding performance during training, tagging, or both?

**Comment by Horsmann** [comment]
Tagging. I have to look into the training part again. If I can avoid that I have to hold the entire training-file string in memory it still might work for training too.

**Comment by Horsmann** [comment]
@reckart How do I retrieve the feature store? I would want to read directly from the feature store when I reach `CRFSuiteTestTask`

**Comment by reckart** [comment]
@habernal featurestore - no idea, probably @daxenberger or @zesch can help.

**Comment by zesch** [comment]
Why do you want to retrieve the FeatureStore in the test task?

**Comment by Horsmann** [comment]
I try to speed up the training process of CRFSuite. A chance for that is a reduction of HDD I/O. Instead of writing the training file file to disk and than read this file we could start CRFsuite in a mode where it receives the data from STDIN.
I would need access to the feature(s) (train and test) to do that. At the moment I only can access the training file in the file system which doesn't help me much.

For bigger data sets (WSJ-size) I should win quite some time. The training files the DataWriter creates wouldnt be used anymore by CRFsuite and would become a debug-help. This would allow it to zip those files. They get quite large at the moment depending on the data set and features used up to 20GB for WSJ settings.
To accomplish that I need access to the feature store in Task to create the train-file information on the fly and provide them to CRFsuite.

**Comment by zesch** [comment]
Thanks for the explanation.

At the moment, all features are extracted in the FeatureExtraction task and the feature store is then persisted.
If you want to skip that step, we would have to merge the FE and Test tasks somehow.
We haven't done that for several reasons so far, including that the FE task doesn't know about the ML framework being used, but writes the contents to whatever format the specific ML framework needs.

**Comment by Horsmann** [comment]
> FE task doesn't know about the ML 

Ideally, I would want to access the feature store as Lab dimension i.e. add a discriminator and receive it. Is it possible to push the store into such a dimension and make it available even after a Lab experiment launched? 
I could then access it without changing any interfaces which I would want to avoid.

I essentially reimplemented the DataWriter as Iterator. All it needs is the data source featureStore.

**Comment by zesch** [comment]
How should that work?
The feature store is a large memory structure that could possibly amount to several gigabyte.
What we could perhaps pass is a reference to the data structure assuming that we can keep it alive between tasks somehow.

**Comment by Horsmann** [comment]
A reference would be fine - that is what I had in mind when mentioning exporting as lab dimension. Not a full copy but rather a reference on it. 
As soon as I would have to rebuild the Store myself or anything alike the runtime gains would be lost anyway - so I would have to be a reference on the store(s) created by the `Extract*` tasks

Is there a lab-trick to keep a data structure alive that is created in one task and make it available later in other tasks so that I can access it again?

**Comment by daxenberger** [comment]
You could of course serialize the feature store as-is after the ExtractFeaturesTask, and then access it from TestTask, but that doesn't help to avoid I/O.
@reckart is there a way to keep objects in the memory across DKPro Lab tasks? It sounds a bit unintuitive to me.

**Comment by reckart** [comment]
DKPro Lab currently does not support maintaining specific objects in memory between tasks. Mind that it would not in general be feasible to do that in a naive way. Consider T1 producing an object which T2 needs. While the parameter space for is walked, in some points, T2 can run based on previously created output from T1 while in other cases T1 needs to be re-run. I think there is no guarantee that tasks executions where objects could be kept in memory are always adjacent in the parameter space.

So what could be done is setting up a cache. T1 would still store its object to disk, but the copy would also be kept in the cache. So when T2 wants to access the object, it would first look in the cache - and only obtain the object from disk if it is no longer available in the cache. 

Such a functionality could be implemented in the DKPro Lab StorageService. We already have a `CachedFileSystemStorageService` (thanks to @dodinh), but so far it caches only metadata, not actual data. The present API would need to be extended, because right now the StorageService doesn't know the object it is storing (and thus cannot cache it) - it only knows that there are some stream producers/consumers.

**Comment by Horsmann** [comment]
Thanks for the explanation. I think CRFsuite won't get any faster then it is right now.

**Comment by Horsmann** [comment]
The `__BOS__` and `__EOS__` do not seem to respected by `crfsuite`. By trial & error I figured out that the linebreaks between the sequences are essential for the end-result.
