### ISSUE TITLE
Log one message at INFO level for each CAS as feedback to the user

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#349]
We need here and there more log-messages. In sequence classification for large data sets `org.dkpro.tc.core.task.uima.ValidityCheckConnector process(103)` is the last log message you see for a rather long time. 

There should be more logging to give the user the feeling that there is still some progress. For CRFsuite settings this is the last message you will see before the classifier starts to read in the data.

**Comment by Horsmann** [comment]
I increased the verbosity of the log messages quite a bit. I might be even a bit too much now, but I think more is better in this case.

Now you actually see which classes tc executes and how much time is spend there. That is helpful for better understanding the workflow of tc and gives you feedback for each CAS processed. I had to add a few dummy logger classes which only purpose is logging.

**Comment by zesch** [comment]
Maybe this shouldn't be at the lowest logging level.
Tobias Horsmann notifications@github.com schrieb am Do., 5. Mai 2016 um
13:21:

**Comment by Horsmann** [comment]
I removed some logging and reduced the log level to `fine`

**Comment by Horsmann** [comment]
You see now the start of the processing logged on `INFO` and the user-preprocessing to see how much time the own preprocessing takes.

**Comment by Horsmann** [comment]
There a log messages on various level. A lot of things are logged by `lab` in the background. I now added additionally a log-message for the meta collection process and feature extraction. One log-message for each CAS. 
If you use only the TC logging you should now still get feedback from the various "steps" in the workflow for each CAS. For small CAS this means still a lot of spam, but I think it helps (new) users a lot to see that a) something is happening and TC did not freeze b) where it is happening.
