### ISSUE TITLE
Make DKPro-TC pipelines/models re-usable as DKPro components

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-tc#35]
Originally reported on Google Code with ID 35

```
To increase the re-usability of models trained within DKPro-TC pipeline, we should make
them available as DKPro components. Like this, they can be used outside DKPro-TC and
users can re-use them without having to set any model parameters etc.
```

Reported by `daxenberger.j` on 2013-07-23 13:48:52
- **Blocked on**: #6, #34

**Comment by Horsmann** [comment]
This one can be closed, too?

**Comment by daxenberger** [comment]
I think so. A demo for reusing SVMhmm models would be nice.

**Comment by Horsmann** [comment]
There is a `SVMHMMSaveAndLoadModelTest` which is the same as for CrfSuite?

**Comment by daxenberger** [comment]
Ah, in the test package. Alright, I missed that one. Ok, fine. I think we can close this.
