### ISSUE TITLE
Experimenting with Mallet reimiplementation

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#352]
Mallet is at the moment `Deprecated` since release `0.7.0` it has been removed during `0.9.0-SNAPSHOT` to ease maintenance of code.

If Mallet is to be revived the module should be reimplemented from scratch. The old version of `Mallet` is parked on a separate branch as reference `mallet_issue352` .

Furthermore note there are new releases of Mallet which should be use

http://search.maven.org/#artifactdetails%7Ccc.mallet%7Cmallet%7C2.0.8%7Cjar
https://github.com/mimno/Mallet

**Comment by Horsmann** [comment]
I added a basic runnable version for `sequence classification`. CRF seems to work in various configurations but HMM keeps failing during the evaluation step.

The code is much more readable than before. It would be cool to get this HMM running but I am out of ideas what is wrong.

**Comment by Horsmann** [comment]
.

**Comment by daxenberger** [comment]
Is mallet fully integrated now? Did you manage to get HMMs working?

**Comment by daxenberger** [comment]
and how dies this issue relate to #377?

**Comment by Horsmann** [comment]
I threw my prototype away. However tries this again better starts from scratch again. This was in no proper state as nothing was really working or rather randomly failing. 

I closed this issue and reopened it to avoid that anyone tries to use my `faulty` version as template.
