### ISSUE TITLE
Enable passing CollectionReaderDescriptions instead of defining reader dimensions

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#353]
At the moment a user have to define 2 dimensions for a reader. Tc builds in the backend a collection reader description from those information. 

i.e.

```
 dimReaders.put(DIM_READER_TRAIN, Reader.class);
        dimReaders.put(DIM_READER_TRAIN_PARAMS, Arrays.asList(Reader.class,
                languageCode, Reader.PARAM_SOURCE_LOCATION, trainFolder,
                Reader.PARAM_POS_MAPPING_LOCATION, posMapping,
                Reader.PARAM_PATTERNS, "*.txt"));
```

it would be good if a user could just initialise the collection reader and pass it as parameter to TC/Lab. This would make using TC more similar to using Core at least in the sense of specifying the readers.

**Comment by Horsmann** [comment]
Change is surprisingly easy just adopting the demos is tedious work ~

@reckart Do you have a code snippet how a collection reader description initialisation has to look like in Groovy?

**Comment by reckart** [comment]
Puh... the problem is how lab handles discriminator values.

If you do this "naively", then you'd probably in the best case end up storing the whole XML descriptor in a discriminator and thus in the properties file. In the worst case, you'd just store something like a object instance identifier like `SomeReader@81def3ce` which is not stable across runs. That's both not what you want. 

So I was always suggesting to use `Discriminable`s. Cf. 
- org.dkpro.lab.groovy.task.ClosureDimensionTest
- org.dkpro.lab.groovy.task.DiscriminableClosure
- org.dkpro.tc.core.util.ExperimentUtil.NamedArrayList<T>

**Comment by reckart** [comment]
@Horsmann rel. to reader description in Groovy: the same as in Java, no?

**Comment by Horsmann** [comment]
Is it? I don't know I am not sure if I ever saw a Groovy program that uses DKPro components so I assumed there are some subtle differences? 
I have to adapt the Groovy test cases to using a the reader description - so any solution would work for me that make the Groovy tests pass again.

**Comment by reckart** [comment]
See e.g. https://dkpro.github.io/dkpro-core/groovy/recipes/convert-conll2006-to-conll2009/

**Comment by reckart** [comment]
@Horsmann for curiosity: what is actually stored in the `DISCRIMINATORS.txt` files for the readers now?

**Comment by Horsmann** [comment]
Hmm and endlessly long text string (72k characters) that makes scrolling in the document really slow.
Is there a way to get a prettier human-redable text?

**Comment by reckart** [comment]
Well, for instance by naming the reader configurations using a Discriminable... cf. the classes I mentioned above.

If you are sure that the endlessly long string is at least reproducible and consistent (and not subject to potentially random variations, e.g. because iteration order in HashMaps is not defined), you could also consider extending Lab to allow storing a hash of the string instead of the string itself (maybe storing the string outside the `DISCRIMINATORS.txt` in a separate file for debugging/recording purposes.

**Comment by reckart** [comment]
That is a proper hash (SHA1 or better), not like Java hashCode() ;) I only have a very rough idea that this should work, it may take a bit working out the details.

**Comment by Horsmann** [comment]
So the easiest solution would be to make a class that implements `Discriminable` which gets in the Constructor a `CollectionReaderDescription`?

Is there an easy way to implement the `CollectionReaderDescription` it has like thousands methods?
Ideally I wont want something like this:

Implement `CRD` and `Discriminable` and do: 

```
 CollectionReaderDescriptionExtendedByDiscriminableInterface readerTrain = CollectionReaderFactory.createReaderDescription(
                NERDemoReader.class,

```

**Comment by zesch** [comment]
If I understand that correctly, you could subclass CRD and implement Discriminable there.
You then only need to return a DiscriminatorValue that is unique and readable.

**Comment by reckart** [comment]
I think it should be possible using a dynamic proxy in a decorator pattern-like style. I used something similar for the DiscriminableClosure. 

I guess it should be possible to implement a generic DiscriminableObject class. It would implement the Discriminable interface and would be used to proxy an instance of any other object that implements interfaces (e.g. CollectionReaderDescription). The result should be a dynamic proxy instance that is both: Discriminable and a CollectionReaderDescription.

**Comment by reckart** [comment]
Some maybe useful reference:
- https://gleichmann.wordpress.com/2007/11/22/mimicry-in-action-dynamically-implement-an-interface-using-dynamic-proxy/
- http://www.ibm.com/developerworks/library/j-jtp08305/

**Comment by reckart** [comment]
@zesch I don't think you'd want to try subclassing CRD - UIMA/uimaFIT creates these internally, and you'd want to leave it that way I am pretty sure.

**Comment by Horsmann** [comment]
@zesch CRD is just an interface you would have to implement it entirely. 

@reckart ok thanks I take a look into it. As is I don't think it is much of an actual problem its more a matter of style ~ its pretty ugly.

**Comment by zesch** [comment]
ok, I probably should not comment on those issues anymore ;)

**Comment by reckart** [comment]
@Horsmann working with dynamic proxies is something I picked up by working with Spring / JPA / etc. It is not infrequent there.

**Comment by reckart** [comment]
I think you can make this somewhat less ugly by introducing a `HashingDimension` which applies this proxy internally to the values it produces (cf. ClosureDimension).

**Comment by Horsmann** [comment]
@reckart I added a dynamic proxy which seems to work.

Following issues which are no real problems either:
I still want some human-readable infos to be written to the Discriminator.txt
I tried to iterate the meta of a collection reader to get the names of the parameters to put them also into the string that is written to the text-file but I do not get the values I actually use:

When I create a reader like this:

```
DiscriminableReaderCollectionFactory.newInstance(BrownCorpusReader.class, BrownCorpusReader.PARAM_LANGUAGE, "en",
                BrownCorpusReader.PARAM_SOURCE_LOCATION, corpusFilePathTrain,
                BrownCorpusReader.PARAM_PATTERNS,
                asList(INCLUDE_PREFIX + "*.xml", INCLUDE_PREFIX + "*.xml.gz")
```

and print the reader meta data like this:

```
    ConfigurationParameterDeclarations configurationParameterDeclarations = crd.getCollectionReaderMetaData().getConfigurationParameterDeclarations();
        ConfigurationParameter[] configurationParameters = configurationParameterDeclarations.getConfigurationParameters();
        for(ConfigurationParameter p : configurationParameters){
            System.out.println(p.getName() + "/" + p.getAttributeValue(p.getName()));
        }
```

I get this output:

```
useCoarseGrained/null
readToken/null
readPOS/null
readLemma/null
readSentence/null
useXmlId/null
useFilenameId/null
omitIgnorableWhitespace/null
POSMappingLocation/null
POSTagSet/null
sourceLocation/null
patterns/null
useDefaultExcludes/null
includeHidden/null
language/null
```

any ideas why?

**Comment by reckart** [comment]
Try using `org.apache.uima.fit.factory.ConfigurationParameterFactory.getParameterSettings(ResourceSpecifier)`.

**Comment by reckart** [comment]
I think the proxy approach should allow not having to change the type of the variables from CollectionReaderDescription to DiscriminableReaderDescription. The dynamic proxy should continue to exhibit the interfaces implement by the wrapped object - the idea was just to add another interface via the dynamic proxy, namely `Discriminable`.

**Comment by Horsmann** [comment]
@reckart That does work but I changed it in a way that you have to use the CollectionReaderDescription that has `Discriminable` i.e.. calling

```
  Object readerTrain = DiscriminableReaderCollectionFactory.createReaderDescription(
                TextReader.class, TextReader.PARAM_SOURCE_LOCATION, corpusFilePathTrain,
                TextReader.PARAM_LANGUAGE, LANGUAGE_CODE, TextReader.PARAM_PATTERNS,
                TextReader.INCLUDE_PREFIX + "*/*.txt");
        dimReaders.put(DIM_READER_TRAIN, readerTrain);
```

**Comment by Horsmann** [comment]
I didn't see much sense in making it optionally?

**Comment by reckart** [comment]
I was imagining something like this there the dimension handles all the wrapping and making things discriminable:

```
Dimension<CollectionReaderDescription> dimReader = new ReaderDimension(
   createReaderDescription(
                TextReader.class, TextReader.PARAM_SOURCE_LOCATION, corpusFilePathTrain,
                TextReader.PARAM_LANGUAGE, LANGUAGE_CODE, TextReader.PARAM_PATTERNS,
                TextReader.INCLUDE_PREFIX + "*/*.txt"),
   createReaderDescription(
                TextReader.class, TextReader.PARAM_SOURCE_LOCATION, corpusFilePathTrain,
                TextReader.PARAM_LANGUAGE, LANGUAGE_CODE, TextReader.PARAM_PATTERNS,
                TextReader.INCLUDE_PREFIX + "*/*.txt"),
   ...);
```

**Comment by reckart** [comment]
The way you presently do it is basically using encapsulation - for that case, you wouldn't even need a dynamic proxy I believe.

**Comment by reckart** [comment]
What I mean is that your present approach requires introducing and calling the getReaderDescription() method whereas I was suggesting to use a dynamic proxy which directly exhibits the CollectionReaderDescription interface such that you can call all the normal methods on it and _in addition_ it would be an instance of Discriminable such DKPro Lab recognizes it.

**Comment by Horsmann** [comment]
I had that - but this makes using the "Discriminable" Collection Reader Description optional - you could still throw in a normal CollectionReaderDescription and it would work. I thought this shouldn't be possible. The whole effort was made to get a readable string in the Discriminator.txt?

**Comment by reckart** [comment]
If you want the compiler to ensure that the reader is discriminable, then your approach is certainly better. I approached this thinking from another direction where I have some object and want to give it a name without changing all the code that actually uses this object.

**Comment by Horsmann** [comment]
And I am not sure if I understand how to implement the `ReaderDimension` you suggested ... I inherit a class from Dimension and my proxy catches this dimension then i.e. every time Dimension is used?

**Comment by reckart** [comment]
The way I did it in ClosureDimension is to wrap the objects being passed to the dimension internally in the proxy, such that the objects returned from the dimension would all be both, Closures _and_ Discriminable. I did it in the constructor, but it would also be possible to do it e.g. in next().

```
    /**
     * Create a new dimension of closures. These closures directly injected into the parameter
     * space - they are not called (cf. {@link ClosureDimension#ClosureDimension(String, Closure...)}).
     * The key associated with each closure is the value used when the closure used as a 
     * discriminator.
     */
    public ClosureDimension(String aName, Map<String, Closure> aClosures)
    {
        super(aName);
        closures = new Closure[aClosures.size()];
        int i = 0;
        for (Entry<String, Closure> e : aClosures.entrySet()) {
            closures[i] = new DiscriminableClosure(e.getValue(),e.getKey());
            i++;
        }
    }
```

**Comment by reckart** [comment]
In your case, you'd not use a map as parameter, but instead generate the key from the reader description (in the way that you have already implemented).

**Comment by Horsmann** [comment]
I still don't get how to implement this ReaderDimensions(). A dimension has a name that is passed to its super class where are the parameters coming from?

**Comment by reckart** [comment]
Consider something like

```
public ReaderDimension(String aName, CollectionReaderDescription... aReaders)
    {
        super(aName);
        readers = new CollectionReaderDescription[aReaders()];
        int i = 0;
        for (CollectionReaderDescription r : aReaders) {
            readers[i] = Proxy.newProxyInstance(classloader, new Class[] { CollectionReaderDescription, Discriminable }, new ReaderInvokationHandler(aReader) );
            i++;
        }
    }
```

**Comment by reckart** [comment]
Updated last comment to use an actual proper proxy...

**Comment by Horsmann** [comment]
Thanks. I still don't understand why you would treat all ReaderDescription together?

I still have to  assign the readers to a dimension i.e. TRAIN_READER or TEST_READER

So I would want to do something like:

```
 ReaderDimension trainDim = new ReaderDimension(DIM_READER_TRAIN, CollectionReaderFactory.createReaderDescription(BrownCorpusReader.class, BrownCorpusReader.PARAM_LANGUAGE, "en",
                BrownCorpusReader.PARAM_SOURCE_LOCATION, corpusFilePathTrain,
                BrownCorpusReader.PARAM_PATTERNS,
                asList(INCLUDE_PREFIX + "*.xml", INCLUDE_PREFIX + "*.xml.gz")));
```

But this seems a bit redundantly because I now still would have to explicitly put it into the dimension map with the `DIM_READER_TRAIN` key

dimReaders.put(DIM_READER_TRAIN, trainDim);

For this to make really sense and be different from what I have now I would want the `InitTask` to fail if you put in an ordinary reader. 

i.e. that what I have right now is essential the same, no?:

```
   Object newInstance = DiscriminableReaderCollectionFactory.createReaderDescription(BrownCorpusReader.class, BrownCorpusReader.PARAM_LANGUAGE, "en",
                BrownCorpusReader.PARAM_SOURCE_LOCATION, corpusFilePathTrain,
                BrownCorpusReader.PARAM_PATTERNS,
                asList(INCLUDE_PREFIX + "*.xml", INCLUDE_PREFIX + "*.xml.gz"));
        dimReaders.put(DIM_READER_TRAIN, newInstance);
```

**Comment by reckart** [comment]
I may be thinking about this from a slightly wrong angle in terms of how it fits into DKPro TC because I don't see this atm in a concrete example/experiment.

**Comment by Horsmann** [comment]
oh ok.  

In a scenario where you have to provide train/test as separate instances: Is there a way to guarantee that a `collectionReaderDesc` is discriminable without enforcing to use a new data type? The way how it is now makes it optional, but causes no real problems either unless you are concerned about the `DISCRIMINATOR.txt`

**Comment by reckart** [comment]
Without looking at how TC presently works, I would be assuming/thinking/imagining the following:
- either I supply one reader dimension (e.g. DIM_READER) and TC internally splits the data into train and test without me intervening at all
- or there would be two different dimensions that I need to supply, e.g. DIM_READER_TRAIN and DIM_READER_TEST and I would set them independently. In this case, if I wanted to run my experiment on multiple data sets and always would have to set fixed pairs of train/test readers, then I would use a DimensionBundle to group them together.

**Comment by zesch** [comment]
We definitely need two dimensions as train and test might be totally
different corpora.
Richard Eckart de Castilho notifications@github.com schrieb am Sa., 14.
Mai 2016 um 10:19:

**Comment by Horsmann** [comment]
What we could do to enforce a `Discriminable CRD` is to let the factory `DiscriminableReaderCollectionFactory.createReaderDescription` return a `Discriminable`.
The `InitTask` would then expect a `Discriminable` too but would cast it to a `CRD` which of course only works if the `DiscriminableReaderCollectionFactory` is used.

```
        Discriminable readerTrain = DiscriminableReaderCollectionFactory.createReaderDescription(
                ReutersCorpusReader.class, ReutersCorpusReader.PARAM_SOURCE_LOCATION,
                FILEPATH_TRAIN, ReutersCorpusReader.PARAM_GOLD_LABEL_FILE, FILEPATH_GOLD_LABELS,
                ReutersCorpusReader.PARAM_LANGUAGE, LANGUAGE_CODE,
                ReutersCorpusReader.PARAM_PATTERNS, ReutersCorpusReader.INCLUDE_PREFIX + "*.txt");
        dimReaders.put(DIM_READER_TRAIN, readerTrain);
////////////////////////
public class InitTask
    extends UimaTaskBase
{

    @Discriminator(name=DIM_READER_TRAIN)
    protected Discriminable readerTrain;
    @Discriminator(name=DIM_READER_TEST)
    protected Discriminable readerTest;
...
    readerDesc = (CollectionReaderDescription) readerTrain;
}
```

This would ensure that you have a discriminable reader and it is not working to throw in a normal CollectionReaderDescription.

I think this is a bit more elegant than what I had before. 

@zesch @daxenberger opinions on that?

**Comment by reckart** [comment]
I would personally prefer not bothering the user with having to use a special factory that creates discriminables, rather ensure that DKPro TC internally wraps reader descriptions accordingly whenever the user supplies non-discriminable descriptions. I feel this should be an internal implementation detail.

**Comment by reckart** [comment]
Btw. it may even be possible to not fiddle around with the dimensions at all and let the task do the wrapping.

If I remember correctly, then DKPro Lab does
1.  configure the tasks with the current parameter space values
2. then ask the task to persist the values in the DISCRIMINATOR.txt - in this step, the task inspects itself to obtain the values using getters

I think it should be possible to do a transparent wrapping by implementing/overriding a `getReader()` method in the respective task and return a discriminable reader at that point.

Didn't really test it though.

Cf. 
- `org.dkpro.lab.engine.impl.DefaultLifeCycleManager.initialize(TaskContext, Task)`
- `org.dkpro.lab.task.impl.TaskBase.analyze(Class<?>, Class<? extends Annotation>, Map<String, String>)`

**Comment by Horsmann** [comment]
Okay I thought too complicated it is quite easy to do it hidden in the initTask as you said - thx.

**Comment by Horsmann** [comment]
@reckart The `DISCRIMINATOR.txt` still has an extremely long string i.e. not the value my `Discriminable` interface returns. I currently wrap the reader descriptions in the `InitTask` this might be a bit too late? When the `DISCRIMINATOR.txt` written? Also, the Excel files create contain the Evaluationresults also get this endless long text.

It looks like the right place would be somewhere in the Lab code. I think all I can do is going back to defining a new type and force the user to use this type right from the start?

**Comment by reckart** [comment]
Is there some unit test where this can easily be observed/debugged?

**Comment by Horsmann** [comment]
Any demo should show that problem

`org.dkpro.tc.examples.single.sequence.CRFSuiteBrownPosDemo`

**Comment by reckart** [comment]
I tried an override of the initialize(TaskContext) method in InitTask and did the wrapping there. This works in the sense that the discriminable value is stored properly in the DISCRIMINATOR.txt file, but then the imports break because in the next task that imports from the InitTask, the descriptor is again not wrapped.

This quite effectively shows that values need already be discriminable within the parameter space, e.g. through a dimension that wraps the values.

I think the next thing I would go for is to extend DKPro Lab to support registering global discriminables, e.g. something like

```
pSpace.registerDiscriminable(
    CollectionReaderDescription.class, desc -> makeDiscriminable(desc));
```

or creating a new "conversionService" and using something like

```
taskContext.getConversionService().registerDiscriminable(
    CollectionReaderDescription.class, desc -> makeDiscriminable(desc));
```

... not sure what would be the best location to put this.

**Comment by reckart** [comment]
Allowing to register special discriminator handlers for specific classes in a suitable place in DKPro Lab could even entirely remove the need to have them implement the Discriminable interface. The Lab could know if they are discriminable by looking in its internal registry of discriminables instead and looking up a proper naming function instead of using the Discriminable interface methods.

**Comment by Horsmann** [comment]
I think I like the `registerDiscriminable()` :-)
Would it take much time to implement that?

**Comment by reckart** [comment]
It would probably take a few attempts or at least some thinking it through to consider all the requiremnts, find a suiteable place to implement this, and then ensure all the necessary information is available at that location.

I would personally tend towards registering the discriminables in the Lab instance through the TaskContext and then using that information again in Task.analyze(),

**Comment by Horsmann** [comment]
ok. I it is not urgent. Things are working and you don't notice the issue unless you look into the text files.

**Comment by Horsmann** [comment]
@reckart Did you had time to think about this issue?

**Comment by reckart** [comment]
@Horsmann not really. But I'm happy to accept pull requests or even provide commit rights ;)

**Comment by Horsmann** [comment]
@reckart I think I will need a more pointers to address this issue. Which class is dealing at the moment with the discriminables. I do not really find a spot where I could start. Any suggestions ?

**Comment by reckart** [comment]
The method that turns an object into a string which is used in the discriminators file is this one: `org.dkpro.lab.Util.toString(Object)`

**Comment by Horsmann** [comment]
How is your idea with the conversionService  supposed to work. In the initialization method of the Task(?) all `expected` types are set to a fixed mapping function something that would call `getDiscriminatorValue` or is this something the user is supposed to by hand?

By the timing I have to have all information in Lab available by the time `analyze(Class<?> aClazz, Class<? extends Annotation> aAnnotation, Map<String, String> props)` is called. My current hack is called way to late. 
Roughly speaking I would want to move the content of the `analyze` method somewhere in the initialization phase - this is probably where it should happen?

**Comment by reckart** [comment]
(Trying to remember)... I think my idea was that the conversion service would be part of the Lab instance, not of a task, e.g.

```
Lab lab = Lab.getInstance();
lab.getConversionService().registerDiscriminable(...);
```

But instead of always having to go through the static `Lab.getInstance()`, within a task the conversion service should be obtained from the task context. Registering a conversion should probably happen in the same place where the Lab instance is initially obtained and where Lab.run(...) is called. The service would be created through the context.xml - just as the other services (e.g. lifecycleservice, etc.). 

For a more sophisticated solution, I suppose it would be possible to instantiate a [Spring Conversion service](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/validation.html#core-convert) to handle that... or at least be inspired of how it works. - Btw. that is what uimaFIT is currently using for parameter value conversion.

**Comment by Horsmann** [comment]
Do I understand it right that I would have to manually call this `registerDiscriminable` for every project/experiment? Essentially before I call `Lab...run()` I would have to know that I have to set those global-overrides for the train/test reader?!

This is even more ugly than wrapping the `CollectionReaderFactory` with a `TcCollectionReaderFactory` which returns only `CRDs` where the `DynamicProxy` is already set. 
This would allow a user still to ignore the `TcCollectionReaderFactory` and use the normal `CollectionReaderFactory` method version resulting in status quo.

**Comment by reckart** [comment]
The discriminables would have to be registered before the first batch task runs. So I would see three options:
- the top-level task could register the discriminables
- discriminables could be auto-detected in a similar way that Lab detects engines or uimaFIT detects types
- discriminables can be manually registered 

I agree that the last option is ugly, but IMHO it would be the first step on top of which one or both others could be implemented.

**Comment by Horsmann** [comment]
@reckart 
I am drafting such a service atm defining it in the `context.xml` and loading it as service as you suggest. So far I understand things here accessing this `conversionService` then does require a `TaskContext`.

Lab does not have such a context when I would need it for accessing the textual information.
For fixing the problem of this issue, I need in the method `protected void analyze(Class<?> aClazz, Class<? extends Annotation> aAnnotation, Map<String, String> props)` which is located `TaskBase` access to this service. 

How do I access such a service from within the `TaskBase`?

**Comment by Horsmann** [comment]
@reckart I tried to hack something and bumped into yet another problem.
The discriminators are stored in a `Map<String,String>` which becomes a problem for the `CollectionReaderDescription`s.  When I hack in my `conversion` the endlessly verbose description text of the `CRD`s cause problems with some `regEx` checks in `ImportUtils` in the method `matchConstraints(Map<String, String> aDiscriminators,
            Map<String, String> aConstraints, boolean aStrict)`

```
name = org.dkpro.tc.api.type.TextClassificationTarget
supertypeName = uima.tcas.Annotation

}

vendor = NULL
version = NULL

vendor = DKPro Core Project
version = 1.9.0-SNAPSHOT

resourceManagerConfiguration = NULL
$
                                                                                                              ^
    at java.util.regex.Pattern.error(Pattern.java:1955)
    at java.util.regex.Pattern.closure(Pattern.java:3141)
    at java.util.regex.Pattern.sequence(Pattern.java:2134)
    at java.util.regex.Pattern.expr(Pattern.java:1996)
    at java.util.regex.Pattern.compile(Pattern.java:1696)
    at java.util.regex.Pattern.<init>(Pattern.java:1351)
    at java.util.regex.Pattern.compile(Pattern.java:1028)
    at java.util.regex.Pattern.matches(Pattern.java:1133)
    at org.dkpro.lab.engine.impl.ImportUtil.matchConstraints(ImportUtil.java:56)
    at org.dkpro.lab.storage.filesystem.FileSystemStorageService.getContexts(FileSystemStorageService.java:141)
    at org.dkpro.lab.engine.impl.BatchTaskEngine.getLatestExecution(BatchTaskEngine.java:297)
    at org.dkpro.lab.engine.impl.BatchTaskEngine.getExistingExecution(BatchTaskEngine.java:360)
    at org.dkpro.lab.engine.impl.BatchTaskEngine.executeConfiguration(BatchTaskEngine.java:223)
    at org.dkpro.lab.engine.impl.BatchTaskEngine.run(BatchTaskEngine.java:134)
    ... 4 more
```

A large part of the whole Lab constraint checking seems to be string based. Any thoughts on how to deal with that?

**Comment by Horsmann** [comment]
@reckart I have issus with initializing the `conversion service` that I defined in the context.xml.
I am missing somewhere some init step but I don't get where.
When I launch a `CrossValidationExperiment` the `ExperimentCrossValidation` Task is properly initialised with the `ConversionService` being `not null`. Once the first `InitiTask` runs the `ConversionService` `is null` so it seems that for the subtasks the initialization is not performed. Where is that suppose to happen

**Comment by reckart** [comment]
@Horsmann is https://github.com/dkpro/dkpro-tc/issues/353#issuecomment-246180878 still an issue for you?

**Comment by Horsmann** [comment]
no, this should be ok now.
