### ISSUE TITLE
Make document mode to a special case of unit mode

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#355]
Document mode is at the moment implemented as own classification type which does not use any annotation spans but work on the entire document by default. This can be implemented by a unit mode case in which the unit spans over the entire document text. 

Eliminating this difference and making document a predefined unit-mode case would help to reduce the number of features drastically i.e. all document mode features which are redundant to the unit mode feature with the exception of (not) working over an annotation span could be deleted. This would make TC much more easy to understand i.e. the user does not have to be bothered with the intrinsic implementation details and simply can uses the feature he/she sees.

The document mode as processing case would be still available on the front-end though the user is usually looking for `document classification` but internally this can be treated as unit-mode case.
- [x] Add unit test-cases for (Lucene) DFE/UFE that test on a finer level 
- [x] Add assert-statements to unit-tests that run document demos
- [x] Make document mode internally a special case of unit-classification
- [x] Delete *DFE features
- [x] Update Demos
- [x] Rename `TextClassificationUnit` to `TextClassificationTarget`
- [x] Rename interface `ClassificationUnitFeatureExtractor` to `FeatureExtractor`

**Comment by Horsmann** [comment]
@zesch I still want to change the name of the `TextClassification*` annotations. 

`TextClassificationUnit` --> `TextClassificationTarget`

I am bit unsure about the sequence annotation I think this can stay as it is.

**Comment by zesch** [comment]
Sounds both good to me.

**Comment by Horsmann** [comment]
I will rename the `ClassificationUnitFeatureExtractor` to simply `FeatureExtractor` what would remain as special case is `Pair` mode but with Document and Unit being one now this on can be renamed too.

A small victim of the changes is the `NrOfChars` FE. The document and unit feature extractor version are quite different. The DFE does a lot more than just NrOfChars. I took the UFE version instead.

**Comment by zesch** [comment]
This is one of the most often used FEs. It would be good to keep it in some
form.
Tobias Horsmann notifications@github.com schrieb am Di., 7. Juni 2016 um
11:03:
