### ISSUE TITLE
Create integration test that builds and runs a shaded-jar

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#356]
Adding of an integration test that takes a sample project, builds it i.e. `mvn install` it and runs the standalone runnable jar to verify that jar-execution works which is a test-case missing entirely at the moment.

**Comment by Horsmann** [comment]
@reckart I added a project as integration test but this `rat` plugin causes problems again

This is what is in the `rat.txt` plugin seems to be unaware of `integration-test`

```
!????? src/it/org.dkpro.tc.shadedjar-integration/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
 !????? src/it/org.dkpro.tc.shadedjar-integration/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
 !????? src/it/org.dkpro.tc.shadedjar-integration/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
```

The license header checks fails - how do I prevent a license header check for my integration project?

**Comment by reckart** [comment]
Make some conservative changes to the rat configuration in the parent POM (https://github.com/dkpro/dkpro-tc/blob/master/pom.xml#L532) - as little as possible should be excluded. So here I think you should exclude something like `src/it/**/target/**/*`.

**Comment by Horsmann** [comment]
Ok thanks.

What exactly can those `verify` scripts do or not do. The building of the jar file works now, but I still need to execute it. I want to use the verify script for that i.e.

```
import java.io.*;
import java.util.*;
import java.util.regex.*;
import org.apache.commons.io.*;
import java.util.List;
import java.util.ArrayList;

try
{
    List<String> command = new ArrayList<>();
    command.add("java");
    command.add("-jar");
    command.add("target//it/org.dkpro.tc.shadedjar-integration/target/org.dkpro.tc.shadedjar-integration-0.0.1-SNAPSHOT-standalone.jar");
    ProcessBuilder probuilder = new ProcessBuilder(command);
    probuilder.start();
    probuilder.wait();
}
catch( Throwable t )
{
    t.printStackTrace();
    return false;
}

return true;
```

This fails with a parsing error of the script. :/ any idea how I get jar executed?

**Comment by reckart** [comment]
Well, as far as I remember, the script runs after the build of the integration test project and can do basically anything. But it is beanshell (I guess), so maybe it doesn't support the generics?

**Comment by Horsmann** [comment]
@reckart any thoughts on this way of solving it - script does not work:

I added another plugin to actually execute my builded jar and I use an accuracy report in the integration test project to thrown an exception if the expected value is not reached:

```
            <plugin>
                <artifactId>maven-invoker-plugin</artifactId>
                <configuration>
                    <cloneProjectsTo>${project.build.directory}/it</cloneProjectsTo>
                    <settingsFile>src/it/settings.xml</settingsFile>
                    <localRepositoryPath>${project.build.directory}/local-repo</localRepositoryPath>
                </configuration>
                <executions>
                    <execution>
                        <id>integration-test</id>
                        <goals>
                            <goal>install</goal>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.5.0</version>
                <executions>
                    <execution>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>java</executable>
                            <workingDirectory>${project.build.directory}</workingDirectory>
                            <commandlineArgs>-jar
                                ${project.build.directory}/it/org.dkpro.tc.shadedjar-integration/target/org.dkpro.tc.shadedjar-integration-0.0.1-SNAPSHOT-standalone.jar
                                ${project.build.directory}/it/org.dkpro.tc.shadedjar-integration/src/main/resources/a15.xml
                                ${project.build.directory}/it/org.dkpro.tc.shadedjar-integration/src/main/resources/a17.xml</commandlineArgs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by reckart** [comment]
I am pretty sure the script should work. Having this in the pom seems a bit ugly to me. But if you are happy with it...

**Comment by Horsmann** [comment]
@reckart removing the generics helped for fixing the parsing error, but the process builder still does nothing. I am not even sure if the file paths I am using are correct but nothing is failing. The script is executed though when I add an exception to force a fail it fails. An idea what is the problem the logs also the build.log of the integration test show nothing it just silently does nothing. At the moment it fails because I am looking for a file which is not created because the jar is not running.

**Comment by reckart** [comment]
I believe that surefire should consider the script a success or failure depending on whether it returns true or false.

Btw. you it might be a good idea to switch from a beanshell-based script to a groovy script (cf. https://maven.apache.org/plugins/maven-invoker-plugin/integration-test-mojo.html#postBuildHookScript).

Try using sysout debugging to check what the current directory is (e.g. `println new File(".")`).

**Comment by Horsmann** [comment]
@reckart I might have a problems with the file paths. The jar is suppose to write a file which the script reads but this does not seem to work. Am I am supposed to read infos in the script that were created by the jar? Dunno what the problem is the script seemingly works locally.

**Comment by Horsmann** [comment]
@reckart is there a way to place a file in a way that the location is resolvable when run on jenkins? At the moment my jar writes a file to the `tmp` folder which my `verify` script tries to read. This works locally but not on Jenkins `i.e. FileNotFoundException`

**Comment by reckart** [comment]
Write your stuff somewhere under `target` - do not use the system tmp.

**Comment by Horsmann** [comment]
This does not work either. Jenkins seems to have problems with `target/` too. I looked into the folder structure that is created and it seems that the creation of the file is the problem. Is this maybe a permission issue?

**Comment by reckart** [comment]
How about adding some logging to AccuracyReport telling us where that report actually wrote the file? I don't think the problem is with the verify script. Does the report even run?

**Comment by reckart** [comment]
Does the invoked java process return with a success code or does it produce an error? Try calling redirectError() and redirectOutput() on the builder so that we have a better chance of seeing the output it produces.

**Comment by Horsmann** [comment]
Jenkins does not execute my jar as it seems. When run locally I see `sys outs` now from the process i.e. normal output and also error out. Nothing shows up in the Jenkins log so I assume my jar is not run.

The evaluations script is suppose to run the jar like this - this should work?:

```
 def command = new ArrayList();
    command.add("java");
    command.add("-jar");
    command.add("target/it/org.dkpro.tc.shadedjar-integration/target/org.dkpro.tc.shadedjar-integration-0.0.1-SNAPSHOT-standalone.jar");
    command.add("target/it/org.dkpro.tc.shadedjar-integration/src/main/resources/a15.xml");
    command.add("target/it/org.dkpro.tc.shadedjar-integration/src/main/resources/a17.xml");
    def probuilder = new ProcessBuilder(command);
    def p = probuilder.start();
    p.waitFor();
```

**Comment by reckart** [comment]
Maybe java is not on the path? As I said: check for the return code from the process and add redirectError() and redirectOutput().

**Comment by reckart** [comment]
When comparing float/double values always allow for a small delta. That is why JUnit asserts for these types always have a delta parameter.

**Comment by ferschke** [comment]
I think you can use java.lang.Double.compare().
Be aware that it treats equality of two Double.NaN or two zero-values with opposite
signs differently than ==, but that should not be an issue.

Or ­ maybe BigDecimal is a good alternative? Shouldn¹t have this issue and
you can freely define the precision.

-Oliver

From:  Richard Eckart de Castilho notifications@github.com
Reply-To:  dkpro/dkpro-tc
<reply+00076ed9ccb7bcd7d374aa9a32ff2ed91370810da0937fc192cf000000011366b7749
2a169ce0961b9e5@reply.github.com>
Date:  Wednesday, June 1, 2016 at 10:47 AM
To:  dkpro/dkpro-tc dkpro-tc@noreply.github.com
Subject:  Re: [dkpro/dkpro-tc] Create integration test that builds and runs
a shaded-jar (#356)

When comparing float/double values always allow for a small delta. That is
why JUnit asserts for these types always have a delta parameter.


You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/dkpro/dkpro-tc/issues/356#issuecomment-223016077 , or
mute the thread 
<https://github.com/notifications/unsubscribe/AAdu2TLS7UfdKq3C0NAN8NR__PU_pf
5Sks5qHZt0gaJpZM4IpWZz> .

**Comment by Horsmann** [comment]
Ok thanks for the feedback. I solved this one now by using integers. The floating points were not really of importance. The script also has a `baseDir` variable which fixes the path issue. Jenkins builds again.
