### ISSUE TITLE
Speed up sequence tagging by using sparse-feature mode as default

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#358]
We have many features i.e. `lucene-ngrams` which return binary decisions. At the moment we use for almost everything the `DenseFeature` store which requires a FE to always return a value even if a value is not set.

If you try to use the SparseFeatureStore it eliminates the whole idea of `sparse` because it is not reliably determinable if a feature value is an actual value or just a value that expresses `not-set` and the sparse feature store turns into a dense feature store.

We need to introduce a protocol that allows us to tell if a value is value that represents `not set` to sort those out if the sparse feature store is used.

This will strongly benefit classifiers that can work with sparse features. At the moment mostly Crf which has been used since `0.7.0` with dense features although it can deal with sparse features.

**Comment by Horsmann** [comment]
@zesch Switching to the sparse feature mode is extremely effective. train/test on WSJ takes now only 20 minutes with a peak of like 20GB RAM usage. If needs be this might even run on a normal workstation with some HDD paging. The training itself is extremely fast now. CRF finishes like in an instant.

Software design issues:
- a MLA has now a feature store method which essentials makes the MLA adapter decide which store is used
- I will add a switch to override the MLA choice by providing an own dimension
- Weka seems to offer sparse features too but the data writer as is works only for dense

**Comment by zesch** [comment]
IIRC dense is the default and sparse can be enabled via a parameter if needed.

**Comment by Horsmann** [comment]
For the moment `Crfsuite` and `SvmHmm` use by default the `SparseFeatureStore` simply because it offers speed benefits here. Any other MLA sticks to the `DenseFeatureStore`. I experimented with Weka and switching to `Sparse-mode` seemingly works, but I am not touching this any further
