### ISSUE TITLE
Each processing mode should generate a result file in its TestTask folder

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#382]
We should revive the `result.txt`. Each Adapter should write a plain text file into its ´TestTask´ folder.
This should be implemented as  report which is added by default in the background so that it is always created which is more a convenience feature.
The information written to this file should depend on the processing mode i.e. document/sequence might be ok with a simple accuracy value while regression needs some squared-error or alike.

**Comment by zesch** [comment]
+1
This would make debugging a lot easier.

**Comment by Horsmann** [comment]
I guess I would then just `hard-code` another report into the `ExperimentTrainTest` and `ExperimentCrossValidation` setup. Or do you see any other suited places to do that?

**Comment by Horsmann** [comment]
@zesch @daxenberger Which measures make sense for multi label? I write now accuracy, micro F1 and macro F1 for `singleLabel`. Are these sufficient for `multi label` or which measures would one expect there?

I also would want to avoid to print all measures as this might be a bit too much information.

**Comment by Horsmann** [comment]
@reckart Is there a way to control the order of the reports that are being executed? I want to add a report in the background `ExperimentTrainTest/ExperimentCrossValidation` which depends on the output of another report `id2outcome`. The `set` data structure unfortunately makes this impossible as I cannot guarantee that this file already exist when my new report runs.

**Comment by reckart** [comment]
You can change the lab code to turn the set into a list.

**Comment by Horsmann** [comment]
fine, give me commit access  -.-*

**Comment by reckart** [comment]
done :)

**Comment by reckart** [comment]
@Horsmann mind that development in the Lab repo takes place on the "development" branch
not on the master branch!

**Comment by Horsmann** [comment]
@reckart snapshot builds are created from the `development` branch and only for releases you merge into master?

**Comment by reckart** [comment]
Yep

**Comment by Horsmann** [comment]
@reckart The snapshot version of lab is wrong. Can I bump this up to 0.13.0-Snapshot?

**Comment by reckart** [comment]
@Horsmann I merged master back into development. The version should be correct now.

**Comment by reckart** [comment]
@Horsmann please check the style of commit comments in DKPro Lab and use it as well, e.g.:

```
#95 - replaced set by list
```

instead of

```
Issue #95: replaced set by list
```

Best look at a few comments to see how the style works.
