### ISSUE TITLE
Package path of machine learning adapter is wrong

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#389]
The project structure has been renamed some time ago and introduced `dkpro-tc-ml-*` as project prefix for the machine learning adapters.

The package name has not been updated for :
- [x] Weka
- [x] Crfsuite 
- [x] Svmhmm

**Comment by Horsmann** [comment]
`Crfsuite` and `svmhmm` uses binary that are installed with the package url.
The hard coded string in the respective classes has to be updated to the new url and `someone` with privileges has to upload the binaries with the new package url into artifactory.

**Comment by Horsmann** [comment]
@reckart could you please upload the crfsuite binary with the new package path into the ukp artifactory?

**Comment by Horsmann** [comment]
@reckart I also updated the `svmhmm` binaries. I tried adding my `artifactory` to the TC pom but I don't get why my Jenkins is not even trying to use the location. It only accesses the UKP artifactory where it doesn't find the binary. Any idea why my repository is ignored?

**Comment by reckart** [comment]
Maybe you are using a settings.xml that prevents it? But I'd prefer if we could keep all the model data/binaries data in a single canonical repository.

**Comment by Horsmann** [comment]
Okay, could you please upload the svmhmm binary then too :)

**Comment by Horsmann** [comment]
I added an installation script for `svmhmm` which didn't exist before. In the source folder `scripts`

**Comment by Horsmann** [comment]
I got access to the models rep. I uploaded the svmhmm binary myself

**Comment by reckart** [comment]
@Horsmann :)

**Comment by reckart** [comment]
@Horsmann Regarding the repo: the idea is to run the script with default settings, which will deploy the model into a "staging repository". You should add this staging repo to your local build and check that the artifacts there are ok. When happy with the artifacts, they should be moved/copied to the actual model repository. @daxenberger I think @Horsmann might require delete permissions on the staging repo in order to perform the move operation... @Horsmann could you please check that?

**Comment by Horsmann** [comment]
@reckart Do you have an idea where this error is coming from

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:analyze (default-cli) on project dkpro-tc-ml-crfsuite: Cannot analyze dependencies: Trying to force use of dependencies which are not declared: [org.dkpro.tc:org.dkpro.tc.crfsuite-bin]
```

Something is somewhere using the old binary. I removed this dependency and updated it with the new one, but I don't know how to find the problem?

**Comment by reckart** [comment]
See https://github.com/dkpro/dkpro-tc/blob/master/dkpro-tc-ml-crfsuite/pom.xml#L106

**Comment by Horsmann** [comment]
Oh there! Thanks!
