### ISSUE TITLE
Weka Id2Outcome TestCase needs update

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#390]
@daxenberger 
There is a test case in Weka which uses a pre-computed *.bin file which contains a hard coded package path. 
This path changed with renaming of the package structure in #389 

The test case `testGenerateOutcomeIdPropertiesMultiLabel()` in `OutcomeIDReportTest` fails now due to this mismatch of the package path.
Could you regenerate the *.bin file one more time with the new package path? Or even better, add a file that generates a new one. Changes to the path name might occur again in the future.

**Comment by daxenberger** [comment]
The binary file is gone now. Should prevent future problems of this type.
