### ISSUE TITLE
Liblinear & Libsvm module ignores instance ID

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-tc#393]
As a consequence, id2outcome reports of this module do not contain the names of instances, but only dummy placeholders.
To fix this, the DataWriter would need to create a separate file with a mapping from instance indexes to Instance Ids (=names), which could then be used by the TestTask/report to map indexes to instance names.

**Comment by Horsmann** [comment]
You mean if the suffix information of the instance id is set this information is lost?

**Comment by daxenberger** [comment]
> You mean if the suffix information of the instance id is set this information is lost?

Basically, yes. It is not transferred from features extraction to testing/predicting.

**Comment by Horsmann** [comment]
Will you take care of this?

**Comment by daxenberger** [comment]
> Will you take care of this?

Probably not before the release ;-)

**Comment by Horsmann** [comment]
@daxenberger can you pull the last change and try again?

**Comment by Horsmann** [comment]
@daxenberger I close this for the moment - I hope I fixed it the unit test cases use the suffix information now.

**Comment by daxenberger** [comment]
Confirmed. Works now.
