### ISSUE TITLE
Lucene Index size depends on number of CAS that are processed

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#396]
During testing with NGrams I noticed that when training models there is a subtle but maybe important dependency between the number of CASs that are created and the size of the model.
The more CAS are processed the larger the model becomes because the Lucene index requires more HDD disc space. This effect seems to be related to how we use the Lucene index-

I had a little test-run in which I read each sentence as single cas which resulted in like 9644 documents in the index reaching something around `5 MB` while a comparison experiment with another reader which read 1000 sentences into one CAS had only 4 resulting in `0.7 MB`

This scales up quite linear, trained models thus become extremely large when for some reason the reader reads only few sequences into one CAS.

**Comment by Horsmann** [comment]
@daxenberger @zesch Is there a reason why the lucene index is used as count-storage but not for actually querying the most frequent words? If a ngram is added as document (not as field, which is how it is done at the moment) then a field for counting can be added. This would allow querying the documents where this field is top-K highest. 

Why this unorthodox usage of Lucene?

**Comment by daxenberger** [comment]
> Why this unorthodox usage of Lucene?

I honestly don't remember. Might be due to legacy reasons.

**Comment by Horsmann** [comment]
Ok, I don't expect much performance gains in changing the query-behavior but I was wondering what lead to the current way of using the index. Might be related to the pair-mode.
