### ISSUE TITLE
Manual pages need an update

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#397]
The manual website is a bit outdated and should be adapted / re-written to fit the `0.9.0` release. Latest documents refer to `0.6.0`

**Comment by daxenberger** [comment]
Adressed some issues in Getting Started and FeatureExtractor documentation in 886d43e62c12197aaf07320f2e61ad6365504983 and a5e7f89ea88ea40bc70bb658a0af44a2d4d41e22.

**Comment by Horsmann** [comment]
@reckart Is there a trick to make the website render similar/identical to the github page view.

The same page looks quite different depending from where it is viewed:
https://dkpro.github.io/dkpro-tc/DKProTcDeepLearning_1_0_0/
https://github.com/dkpro/dkpro-tc/blob/gh-pages/pages/DKProTcDeepLearning_1_0_0.md

In particular, the code block part is ugly when viewing via `github.io`.

**Comment by reckart** [comment]
I'm not deeply familiar with the code-rendering functionalities of Jekyll and how they interact with the CSS from our template.

For documentation, I prefer using Asciidoc: https://dkpro.github.io/dkpro-core/releases/1.9.0/docs/component-reference.html

You can also check out the markdown for the DKPro Core "recipes" such as https://dkpro.github.io/dkpro-core/groovy/recipes/convert-penn-combined-to-tiger-xml/ (https://github.com/dkpro/dkpro-core/blob/gh-pages/_recipes_groovy/convert-penn-combined-to-tiger-xml.md)

**Comment by reckart** [comment]
TC already has aciidoc documentation: https://github.com/dkpro/dkpro-tc/tree/master/dkpro-tc-doc/src/main/asciidoc
