### ISSUE TITLE
ExperimentTrainTest does not set 'isTesting' flag

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#404]
This flag is set for CrossValidation but not for TrainTest experiments

**Comment by daxenberger** [comment]
Is this flag actually used in TrainTest scenarios?

**Comment by Horsmann** [comment]
Well, the `ExtractFeatureConnector` has this code-block:
and this `applyFeatureNameFilter ` should have never been executed for train-test.
This is essentially why I am asking in the #403 regarding this feature-name filtering - this seems to be uncritically if it is not done. Train-Test worked quite well without it.

```

    @Override
    public void collectionProcessComplete()
        throws AnalysisEngineProcessException
    {
        super.collectionProcessComplete();
        
        applyFilter();

        // write feature names file if in training mode
        if (!isTesting) {
            writeFeatureNames();
        }
        // apply the feature names filter
        else {
           applyFeatureNameFilter();
        }

        // FIXME if the feature store now determines whether to use dense or sparse instances,
        // we might get rid of the corresponding parameter here
        // addInstanceId requires dense instances
        try {
            DataWriter writer = (DataWriter) Class.forName(dataWriterClass).newInstance();
            writer.write(outputDirectory, featureStore, !featureStore.supportsSparseFeatures(), learningMode, applyWeighting);
        }
        catch (Exception e) {
            throw new AnalysisEngineProcessException(e);
        }
    }
```

**Comment by daxenberger** [comment]
Ok so this seems to be a bug. I personally haven't used FeatureFilters, and I could life without them in. Maybe @zesch wants to comment more on the matter?

**Comment by zesch** [comment]
I think we need to distinguish between Filters in general and the FeatureNamesFilter.
I don't really know anymore about the latter.

Filters in general are IMO a useful concept.
