### ISSUE TITLE
Reduce Runtime of Test on Jenkins

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#413]
The tests have become extremely time consuming (~30min) for the example project without the example-groovy project.

Its time to clean up and tune the classifier settings to run only few iterations. If possible summarize test case to a single demo.

**Comment by Horsmann** [comment]
@reckart @daxenberger the `Groovy` test cases in the `tc-integrationtest` project - how are they different from the one in `examples-groovy`.
This looks pretty redundant to me? the groovy examples do create dimensions and run cross validation experiments?
Can I delete this project? It seems just to use CPU time every time we build with actually testing anything (that would not yet be covered).

**Comment by reckart** [comment]
Do the groovy examples actually have asserts? Does the integration tests have asserts? Are the groovy examples built and run during a full build?

**Comment by Horsmann** [comment]
No, all Groovy are `does-it-crash-if-executed`-testing. I would keep the test cases in the groovy project but would want to drop the integration project.
