### ISSUE TITLE
Clean up dependencies

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-tc#424]
Ensure that the modules in DKPro TC do not declare more than the required dependencies. Also ensure that test dependencies are marked with the scope `test`.

**Comment by Horsmann** [comment]
Which one do you mean? The mvn dependency calls show no `used but not declared` nor `unused declared` ?
Jenkins wouldn't build if this would be the case, wouldn't it?

**Comment by reckart** [comment]
Yep. I'm locally checking if the scopes are also ok.

**Comment by reckart** [comment]
It shouldn't be a blocker though. If you want to release before I am done with it then so be it.
