### ISSUE TITLE
Create Super-Module for LibSvm/Liblinear

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#434]
Both modules use the same data format and could use a shared super-module. 
This would reduce code redundancy considerably. Except for the actual API calls to the backend-SVM, the TC Code is identical (in behavior not in actual line-of-codes).

@zesch any idea for a new module name for this middle-hierarchy module ?

**Comment by zesch** [comment]
LibX :)
Tobias Horsmann <notifications@github.com> schrieb am Fr. 2. Feb. 2018 um
21:36:

**Comment by reckart** [comment]
Isn't a shared module that is used by two other modules lower in the hierarchy?

**Comment by Horsmann** [comment]
Hm, depends how you look at it. If you think of the TC project as a (computer science) tree then the leafs are the lowest level, i.e. most specific, with this LibX project being an intermediate branch between the root and the leaf for the LibSvm and Liblinear project?

It might be possible to let SvmHmm use the same top-level project and #428 might benefit from it, too. Some name that express `almost-standard-data-format-for-many-machin-learning-tools-project` would be good :)

**Comment by Horsmann** [comment]
how about `dkpro-tc-ml-svm-io`, and -liblinear and -libsvm would get a dependency on this project?

**Comment by reckart** [comment]
I suppose in DKPro Core, it would be called `dkpro-core-io-<formatname>` - no idea what a suitable format name would be in this case though... is it again a "tab separated format" (tsv)... or better to name it after the first/most prominent tool that uses it...?
