### ISSUE TITLE
Reader for typical machine learning data formats

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#444]
We should have readers that explicitly read the typical machine-learning data formats, i.e. a dedicated reader that reads `TEXT TAB LABEL` or `TEXT TAB DOUBLE`.

The readers should then automatically annotated `TextClassificationOutcome` and other data types that TC needs. I guess many people will actually start with such a `de-facto standard` flat-file format.
We should have readers that supports this format and are also recognizable as such (by their name).

These readers could then also be used for the documentation to walk a user through the pipeline setup using an as simple as possible example. The reader implementation should be as simple as possible, too, no overhead in engineering to have minimal working example of a basic TC reader. The reader is still the hardest part for getting started with UIMA/TC. Lowering the threshold for beginners would certainly be helpful?

I was thinking of adding an `-io` project with one or two readers for the most-frequently used data formats. @reckart is this maybe already contained in DKPro Core ?

**Comment by reckart** [comment]
@Horsmann DKPro Core has all kinds of "CoNLL" readers/writers, but none that has word-tab-value. The main problem here is that we do not know which annotation/feature the value should go to. Of course it would be conceivable to implement a generic parametrizable reader, but nobody has done that so far. Might be a nice addition to Core though.

**Comment by Horsmann** [comment]
@reckart What I have in mind and now also implemented is something like this: https://github.com/dkpro/dkpro-tc/tree/master/dkpro-tc-io/src/main/java/org/dkpro/tc/io

One could define two additional parameters for defining the annotation to which `Text` and `Label` should go to, but this is about the complexity the readers (for the TC use case) should have, imo.

**Comment by Horsmann** [comment]
I added two readers now. Line-wise with label and folder-wise with the folder name as label

**Comment by reckart** [comment]
Looks good for TC - wouldn't fit in this way with core though. But that's fine.
