### ISSUE TITLE
Rename Lucene Features in features-ngram project

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#445]
The Lucene-based features and the project name `features-ngram` are not ideal. With the normalization issue #436, ngram-stuff is only one of the things these features are good for. Furthermore, the naming of the features with the `Lucene*`-prefix is zero informativ to the user. The features should not expose implementation details in their names.

How about `dkpro-tc-features-frequency` as project name? This is closer to what the extractors do, i.e. frequency cut-off related tasks over annotation-types. One could use a suffix `FreqCutOff` for the feature names instead of the `Lucene` prefix, i.e. `CharacterNgramFreqCutOff` or `WordNgramFreqCutOff`

Any objections ?

**Comment by zesch** [comment]
I agree with the Lucene* comment. This should be renamed.
I don't understand why "ngram" is a bad name. That's what the FEs are doing.

Why have the FreqCutOff in the name?

2018-02-10 19:51 GMT+01:00 Tobias Horsmann <notifications@github.com>:

**Comment by Horsmann** [comment]
Okay. I think it is sufficient to just drop the `Lucene` part in the name. The normal token-ngrams could be renamed to 'WordNgrams'.

> Why have the FreqCutOff in the name?

To help understand what they do, the freq-cut off in the name is a good pointer to how these feature work, which makes it easier to understand what they are doing.
Its probably better to tackle this in the documentation.
