### ISSUE TITLE
WordShapeClassifer is GNU license

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#453]
We seem to have a license issue in the `features` project.

This class: https://github.com/dkpro/dkpro-tc/blob/master/dkpro-tc-features/src/main/java/org/dkpro/tc/features/window/WordShapeClassifier.java
is copied from Stanford: https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/process/WordShapeClassifier.java, which is GNU

@reckart This probably cannot be resolved without making the feature project GNU, right?
@betoboullosa You added the classes originally, do you still work with them?

**Comment by reckart** [comment]
The WordShape code from CoreNLP/StanfordNLP cannot be used in our code without making the affected code GPL. It would have to be moved to a separate GPLed module.

Or you'd have to re-implement the code, optimally using a "clean room" approach in which you do actually not look at the original GPLed code.

Or you could ask Manning et al. whether they would consider placing the code under a non-GPL license, e.g. Apache, BSD, MIT etc.

**Comment by Horsmann** [comment]
I expected that much :(. I think this class has been added before the last release, which means this is already contained in the 0.9.0 release. I would delete the classes for now. They can be fished-out the Git if they are needed by someone.
