### ISSUE TITLE
Include majority class and random baselines in reports

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-tc#454]
Would it be possible to always include the majority baseline and random baseline in experiment reports? It may not be obvious to the user that even high fscores are essentially worthless until she looks at the actual prediction files and discovers that the classifier essentially just predicts the majority class.

**Comment by Horsmann** [comment]
I think this should be doable. I will have a look next week. I like the idea.

- [x]  CrfSuite 
- [x]  Weka
- [x]  Lib*
- [x]  DeepLearning-DyNet
- [x]  DeepLearning-Keras
- [x]  DeepLearning-Dl4J
- [x]  Excel-Output `BatchTrainTestReport`
- [x]  Excel-Output `BatchCrossValidationReport`

**Comment by Horsmann** [comment]
What would be a reasonable `majority` value for regression, i.e. mean value of all encountered regression values? Or would one rather have no majority value in case of regression? @zesch

**Comment by zesch** [comment]
doesn't make sense for regression in my view

2018-03-08 11:14 GMT+01:00 Tobias Horsmann <notifications@github.com>:

**Comment by Horsmann** [comment]
@reckart should be available now
