### ISSUE TITLE
Allow passing an outcome converter to TcAnnotator

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-tc#456]
Currently, to use TcAnnotator in a production environment, one has to wrap it in another UIMA component which delegates to the TcAnnotator in its `process` method and after running it picks up the `TextClassificationOutcome` annotations, creates the **actually** desired outcome annotations and then removes the outcomes.

In order to avoid the need for creating a wrapper UIMA component all the time, it might be a nice idea to pass the name of a converter class to TcAnnotator which would be called with the JCas as an argument after TcAnnotator completes its `process` method - thus the conversion can happen within the scope of the TcAnnotator.

**Comment by Horsmann** [comment]
@reckart One could also pass the name of the annotation directly with the field-name? I am not sure how the API looks for this but this would probably most straight forward? It was possible to reference the field of an annotation by a string-name, right?

**Comment by reckart** [comment]
I think the conversion process of outcome to actual annotation may be more complicated than the case that simply creating an instance of AnnotationFS and setting a field on it:

* **the annotation you want to add the outcome too might already exist from a previous annotation step** - e.g. if you have a TcAnnotator which does performs entity linking on NamedEntity annotations that have been created by say StanfordNamedEntityRecognizer.
* **there may be multiple fields to set** - obvious cases could be the label and the confidence score; but the label itself might be split up into multiple fields, e.g. in case of filling in the various features of MorphologicalFeatures
* **the label may require post-processing** - e.g. in the case of BIO-encoded labels which a converter could merge

**Comment by Horsmann** [comment]
Ok. I uploaded a change. There is a test case in the example project in the package `org.dkpro.tc.tcAnnotator` that demonstrates / test using such a conversion annotator.

**Comment by Horsmann** [comment]
@reckart Is the current implementation what you had in mind?
