### ISSUE TITLE
Line-breaks should use System.lineSeparator() 

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#462]
Line-breaks are often hard-coded as '\n'. It would be more clean to use `System.lineSeparator()` which sets them correctly for Windows i.e. `\r\n`

**Comment by reckart** [comment]
I usually do not do this. It makes the code annoyingly unreadable and hardly contributes anything.

**Comment by reckart** [comment]
In fact, if I notice any code in my projects which does this, I usually change it to use simply `\n`.

**Comment by zesch** [comment]
It also might break compatibility when moving a file generated by TC between *nix and Windows machines.

**Comment by Horsmann** [comment]
^^ ok, I am convinced.
