### ISSUE TITLE
Settings metrics for evaluation

### ISSUE THREAD

**Issue by Zepp10x** [dkpro/dkpro-tc#482]
When running a `ExperimentCrossValidation`, the final results file only seems to contain the accuracy for each classifier and fold. Is it currently (version `1.0.0-SNAPSHOT`) possible to add additional metrics (recall, precision etc.) to a `BatchCrossValidationReport`?

**Comment by Zepp10x** [comment]
Are additional metrics currently not supported? In version `0.9.0` the evaluation results file contained additional metrics besides accuracy.

**Comment by Horsmann** [comment]
Hi,

For classification, you should find in the WekaTestTask folder also a file with FScore, Recall and Precision. I am not sure If such a file also exist in the Evaluation folder but in the WekaTestTask it should be there.

Which other metrics are you missing ?

**Comment by Zepp10x** [comment]
Thank you for your hint! Precision & Recall for each fold in a cross validation experiment can be found in the `scorePerCategory.txt` files in the `WekaTestTask*` directories in `DKPRO_HOME`.
