### ISSUE TITLE
Results.xls - experiment results of multiple classifier experiments are not distinguishable 

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#485]
The cannot be separated by the information in the .xls if more than one classifier is used.
This problem is limited to cross-validation experiments. Can be probably solved by reading the DISCRIMINATOR.txt of the ML-tasks and printing them into the Excel file.

**Comment by zesch** [comment]
They used to be because the parameterization was written as one of the
discriminators. Isn’t that the case anymore?
Tobias Horsmann <notifications@github.com> schrieb am Mo. 7. Mai 2018 um
05:04:

**Comment by Horsmann** [comment]
Not anymore. I re-added this but its hard to tell when/where this was lost. I re-introduced this information.
