### ISSUE TITLE
CV id2outcome labels differs to the one in train test

### ISSUE THREAD

**Issue by huangpanzhang** [dkpro/dkpro-tc#524]
As I see, if you do a single label classification using the _VowpalWabbit_ classifier, the output label in _Train_Test_ report is "1" and "2". However, the in the output report of _Cross_Validation_, the label is "0" and "1" (same as other classifiers).

**Comment by Horsmann** [comment]
The combined id2outcome report should respect now the integer mapping from the individual runs. In the case of vowpal wabbit, it should start counting at 1 instead of zero as for the most other machine learning classifiers.
