### ISSUE TITLE
Clone/download sources (OS Windows)

### ISSUE THREAD

**Issue by pkluegl** [dkpro/dkpro-tc#538]
I cannot clone or download the dkpro-tc sources on a Windows machine due to too long filenames.

> error: unable to create file dkpro-tc-examples/src/test/resources/TcAnnotatorTestModelDummy/featureClassFolder/org/dkpro/tc/examples/shallow/serialization/crfsuite/BrownClusterFeature$PointlessInnerClassToEnsureThatInnerClassesAreProperlySerializedAndLoadedToo$1.class: Filename too long
> error: unable to create file dkpro-tc-examples/src/test/resources/TcAnnotatorTestModelDummy/featureClassFolder/org/dkpro/tc/examples/shallow/serialization/crfsuite/BrownClusterFeature$PointlessInnerClassToEnsureThatInnerClassesAreProperlySerializedAndLoadedToo$AnotherOne.class: Filename too long
> error: unable to create file dkpro-tc-examples/src/test/resources/TcAnnotatorTestModelDummy/featureClassFolder/org/dkpro/tc/examples/shallow/serialization/crfsuite/BrownClusterFeature$PointlessInnerClassToEnsureThatInnerClassesAreProperlySerializedAndLoadedToo.class: Filename too long

**Comment by Horsmann** [comment]
Thanks, I will have a look. 

btw.
Which Windows version are you using? Windows 10 does allow long filenames but you have to explicitly enable it in the registry. I think the default is still 256 but longer names should be possible.

**Comment by Horsmann** [comment]
@pkluegl Can you check it out again? The paths should be considerably shorter now.

**Comment by pkluegl** [comment]
Yes, I was able to clone it now. Thank you very much.

I am using Windows 10, but the option in the registry is missing. At least I haven't found it using the available howtos.

**Comment by Horsmann** [comment]
Ok, great! Thanks for reporting.
